### ISSUE TITLE
panic creating transient file in accounts hash calc

### ISSUE THREAD

**Issue by jeffwashington** [solana-labs/solana#33174] opened 2023-09-06 22:16 UTC
#### Problem

mcb5i4hCFKHK26z1pCbAYBB2efHnS2EZMv2bRfFaL7x
panicked at 'Unable to write file within /home/sol/ledger/accounts_hash_cache/transient: Cannot allocate memory (os error 12)', runtime/src/accounts_hash.rs:108:21)

memory use low, 3TB disk free
folder exists
hash calc had just completed within last minute and had completed many times back to back forever.

not too many open file descriptors:
![image](https://github.com/solana-labs/solana/assets/75863576/be74e2e4-b29b-444b-8390-b9e9aff042b1)

```
/home/sol/logs/solana-validator.log.5-[2023-09-01T07:04:22.712541850Z INFO  solana_metrics::metrics] datapoint: os-config vm.max_map_count=2000000i
/home/sol/logs/solana-validator.log.5-[2023-09-01T07:04:22.712541630Z INFO  solana_core::system_monitor_service]   vm.max_map_count: recommended=1000000 current=2000000
/home/sol/logs/solana-validator.log.5-[2023-09-01T07:04:23.968300709Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 1000000
```

<details><summary>Backtrace</summary>
<p>

```
thread 'solAccountsLo06' panicked at 'Unable to write file within /home/sol/ledger/accounts_hash_cache/transient: Cannot allocate memory (os error 12)', runtime/src/accounts_hash.rs:108:21
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: solana_runtime::accounts_hash::AccountHashesFile::write
   3: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &F>::call_mut
   4: rayon::iter::plumbing::Folder::consume_iter
   5: rayon::iter::plumbing::bridge_producer_consumer::helper
   6: rayon_core::job::StackJob<L,F,R>::run_inline
   7: rayon_core::join::join_context::{{closure}}
   8: rayon_core::registry::in_worker
   9: rayon::iter::plumbing::bridge_producer_consumer::helper
  10: rayon_core::join::join_context::{{closure}}
  11: rayon_core::registry::in_worker
  12: rayon::iter::plumbing::bridge_producer_consumer::helper
  13: rayon_core::join::join_context::{{closure}}
  14: rayon_core::registry::in_worker
  15: rayon::iter::plumbing::bridge_producer_consumer::helper
  16: rayon_core::join::join_context::{{closure}}
  17: rayon_core::registry::in_worker
  18: rayon::iter::plumbing::bridge_producer_consumer::helper
  19: rayon_core::join::join_context::{{closure}}
  20: rayon_core::registry::in_worker
  21: rayon::iter::plumbing::bridge_producer_consumer::helper
  22: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  23: rayon_core::registry::WorkerThread::wait_until_cold
  24: rayon_core::join::join_context::{{closure}}
  25: rayon_core::registry::in_worker
  26: rayon::iter::plumbing::bridge_producer_consumer::helper
  27: rayon_core::job::StackJob<L,F,R>::run_inline
  28: rayon_core::join::join_context::{{closure}}
  29: rayon_core::registry::in_worker
  30: rayon::iter::plumbing::bridge_producer_consumer::helper
  31: rayon_core::join::join_context::{{closure}}
  32: rayon_core::registry::in_worker
  33: rayon::iter::plumbing::bridge_producer_consumer::helper
  34: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  35: rayon_core::registry::WorkerThread::wait_until_cold
  36: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-09-06T21:19:35.927609053Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solAccountsLo06" one=1i message="panicked at 'Unable to write file within /home/sol/ledger/accounts_hash_cache/transient: Cannot allocate memory (os error 12)', runtime/src/accounts_hash.rs:108:21" location="runtime/src/accounts_hash.rs:108:21" version="1.16.12 (src:f81349cb; feat:3949673676, client:SolanaLabs)"
```

</p>
</details> 

#### Proposed Solution
debug and fix

**Comment by jeffwashington** [comment] 2023-09-06 22:17
If a validator hits this, it should panic, fail, and restart. There should be no issue with restart. Worst case is many validators hit it around the same time and are restarting. Most validators are creating a new hash calc basically constantly.

**Comment by jeffwashington** [comment] 2023-09-06 22:20
Here's where the files are created:
https://github.com/solana-labs/solana/blob/90d983980e634bfb651fdbc2e797477d8b60f9b4/runtime/src/accounts_hash.rs#L91C32-L97

**Comment by jeffwashington** [comment] 2023-09-06 22:24
#33095
?
@HaoranYi

**Comment by jeffwashington** [comment] 2023-09-06 22:37
[1.16 used `write`](https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write)
This indicates it could return an error.
`write_all` avoids this.

**Comment by steviez** [comment] 2023-09-06 22:50
I believe we have seen this one before; it likely would have been what prompted this PR:
https://github.com/solana-labs/solana/pull/32036

**Comment by jeffwashington** [comment] 2023-09-06 22:59
Very possible. I think `write_all` is the best attempt at mitigation we have so far. #33095 (backport=33175)

**Comment by steviez** [comment] 2023-09-06 23:14
Agreed that #33095 is an improvement as `write` is not guaranteed to write the entire buffer in one go. However, this failure does point to the write itself failing. Ie, we hit the panic and not the assertion failure in this block:
https://github.com/solana-labs/solana/blob/90d983980e634bfb651fdbc2e797477d8b60f9b4/runtime/src/accounts_hash.rs#L102-L113

**Comment by steviez** [comment] 2023-09-06 23:22
Running `sudo dmesg -T`, I see:
```
[Wed Sep  6 21:13:11 2023] solAccountsLo06: page allocation failure: order:0, mode:0xa30(GFP_ATOMIC|__GFP_RECLAIMABLE), nodemask=(null),cpuset=/,mems_allowed=0
[Wed Sep  6 21:13:11 2023] CPU: 1 PID: 1428719 Comm: solAccountsLo06 Not tainted 5.4.0-139-generic #156-Ubuntu
[Wed Sep  6 21:13:11 2023] active_anon:13347168 inactive_anon:721275 isolated_anon:0
                            active_file:21516588 inactive_file:27882583 isolated_file:96
[Wed Sep  6 21:13:11 2023] Node 0 active_anon:53388672kB inactive_anon:2885100kB active_file:86066352kB inactive_file:111530332kB unevictable:18776kB isolated(anon):0kB isolated(file):384kB mapped:160444212kB dirty:13620976kB writeback:27188kB shmem:673764kB shmem_thp: 0kB shmem_pmdmapped: 0kB anon_thp: 0kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
```
It is the same thread as listed below, although there is a 6-min difference in timestamps:
```
[2023-09-06T21:19:35.927609053Z ERROR solana_metrics::metrics] datapoint:
panic program="validator" thread="solAccountsLo06" one=1i
message="panicked at 'Unable to write file within /home/sol/ledger/accounts_hash_cache/transient:
Cannot allocate memory (os error 12)', runtime/src/accounts_hash.rs:108:21"
location="runtime/src/accounts_hash.rs:108:21" version="1.16.12 (src:f81349cb; feat:3949673676, client:SolanaLabs)"
```

**Comment by HaoranYi** [comment] 2023-09-07 01:34
> [Wed Sep  6 21:13:11 2023] solAccountsLo06: page allocation failure: order:0, mode:0xa30(GFP_ATOMIC|__GFP_RECLAIMABLE), nodemask=(null),cpuset=/,mems_allowed=0

order:0  means it tries to allocate 2^0=1 page which is 4Kb. 
__GFP_RECLAIMABLE is used for slab allocations.

It seems that the kernel, kmalloc can't find a continous 4Kb memory to allocate. 
By default, BufWriter use 8Kb for internal buffer. 
I wonder if we are are leaking 4Kb slab page somewhere. 

@steviez can you run `slaptop` on the box and watch for the usage of `kmalloc-4k` slab?

```
$ sudo slabtop 
```

**Comment by HaoranYi** [comment] 2023-09-07 01:48
A potential solution, which may mitigate the pressure for slab cache, is to limit the buffer size to 2Kb, with `[with_capacity](https://doc.rust-lang.org/std/io/struct.BufWriter.html#method.with_capacity). 
The smaller buffer will flush more often and occupy less slab objects.

**Comment by HaoranYi** [comment] 2023-09-07 04:12
I think there might be a problem with AccountHashFile. 

Since there are 65536 bins, there could be 65K hash files. Inside each AccountHashFile, we currently cache the buf writer, which will allocate 7Kb * 65K buffer. That could leads to slab cache OOM. 

I am working on the PR to fix this by cache the File descriptor instead.

**Comment by steviez** [comment] 2023-09-07 09:25
> can you run slaptop on the box and watch for the usage of kmalloc-4k slab?

Here is an instantaneous snapshot from running with `--once` flag.
<details>
  <summary>Full output</summary>
  
```
 Active / Total Objects (% used)    : 31624687 / 32853023 (96.3%)
 Active / Total Slabs (% used)      : 842865 / 842865 (100.0%)
 Active / Total Caches (% used)     : 104 / 170 (61.2%)
 Active / Total Size (% used)       : 5385094.81K / 5778278.63K (93.2%)
 Minimum / Average / Maximum Object : 0.01K / 0.18K / 15.14K

  OBJS ACTIVE  USE OBJ SIZE  SLABS OBJ/SLAB CACHE SIZE NAME                   
22434594 22078891  98%    0.10K 575246       39   2300984K buffer_head            
2361394 2175324  92%    0.57K  84550       28   1352800K radix_tree_node        
2057349 1961797  95%    0.19K  49015       42    392120K dentry                 
775744 704680  90%    0.06K  12121       64     48484K vmap_area              
670604 603961  90%    0.20K  17196       39    137568K vm_area_struct         
660416 591005  89%    0.25K  20666       32    165328K filp                   
655436 485247  74%    1.07K  23600       29    755200K ext4_inode_cache       
516120 447100  86%    0.02K   3036      170     12144K lsm_file_cache         
304368 186177  61%    0.04K   2984      102     11936K ext4_extent_status     
258432 258240  99%    0.06K   4038       64     16152K anon_vma_chain         
176940 175632  99%    0.13K   5898       30     23592K kernfs_node_cache      
165888 165888 100%    0.03K   1296      128      5184K kmalloc-32             
138021 137826  99%    0.10K   3539       39     14156K anon_vma               
118336 116782  98%    0.06K   1849       64      7396K kmalloc-64             
115712 115712 100%    0.01K    226      512       904K kmalloc-8              
 97004  93775  96%    0.59K   1895       53     60640K inode_cache            
 87552  87552 100%    0.02K    342      256      1368K kmalloc-16             
 83328  82822  99%    0.66K   1883       48     60256K proc_inode_cache       
 73984  73472  99%    0.03K    578      128      2312K ext4_pending_reservation
 72448  62988  86%    0.06K   1132       64      4528K kmalloc-rcl-64         
 57248  57248 100%    0.12K   1789       32      7156K pid                    
 54416  54416 100%    0.50K   1723       32     27568K kmalloc-512            
 52084  51748  99%    2.00K   3257       16    104224K kmalloc-2k             
 49504  49504 100%    0.14K   1768       28      7072K ext4_groupinfo_4k      
 48960  48960 100%    0.04K    480      102      1920K pde_opener             
 41922  41249  98%    0.12K   1233       34      4932K jbd2_journal_head      
 41792  41792 100%    0.06K    653       64      2612K ext4_io_end            
 40047  40047 100%    0.19K    954       42      7632K kmalloc-192            
 37485  37485 100%    0.08K    735       51      2940K task_delay_info        
 36880  36848  99%    0.25K   1167       32      9336K skbuff_head_cache      
 34650  34527  99%    0.19K    825       42      6600K cred_jar               
 33988  33755  99%    1.00K   1077       32     34464K kmalloc-1k             
 32802  32802 100%    0.09K    781       42      3124K kmalloc-96             
 30184  30184 100%    0.07K    539       56      2156K eventpoll_pwq          
 28876  28611  99%    0.81K    744       39     23808K sock_inode_cache       
 24168  24067  99%    0.31K    480       51      7680K mnt_cache              
 22784  22784 100%    0.12K    712       32      2848K kmalloc-128            
 22008  20544  93%    0.09K    524       42      2096K kmalloc-rcl-96         
 18508  18508 100%    1.00K    581       32     18592K PING                   
 18246  18218  99%    1.12K    657       28     21024K signal_cache           
 17618  17618 100%    0.69K    383       46     12256K files_cache            
 16983  16659  98%    0.31K    333       51      5328K nf_conntrack           
 16675  14131  84%    0.69K   1490       46     47680K squashfs_inode_cache   
 16245  13266  81%    0.70K    361       45     11552K shmem_inode_cache      
 15120  15120 100%    0.25K    475       32      3800K pool_workqueue         
 14952  14952 100%    0.19K    356       42      2848K skbuff_ext_cache       
 13824  13824 100%    0.03K    108      128       432K fsnotify_mark_connector
 13380  13380 100%    1.06K    446       30     14272K mm_struct              
 10585  10585 100%    0.05K    145       73       580K mbcache                
  9984   9984 100%    0.06K    156       64       624K kmem_cache_node        
  9945   9945 100%    0.05K    117       85       468K ftrace_event_field     
  9857   9857 100%    2.06K    659       15     21088K sighand_cache          
  9792   9792 100%    0.12K    306       32      1224K scsi_sense_cache       
  9744   9744 100%    0.07K    174       56       696K Acpi-Operand           
  9472   9472 100%    0.25K    296       32      2368K dquot                  
  9360   9360 100%    0.44K    260       36      4160K kmem_cache             
  8346   8293  99%    4.00K   1073        8     34336K kmalloc-4k             
  7712   7712 100%    0.25K    241       32      1928K kmalloc-256            
  7200   7200 100%    0.50K    225       32      3600K skbuff_fclone_cache    
  6816   6539  95%    0.12K    213       32       852K kmalloc-rcl-128        
  6059   6059 100%    0.05K     83       73       332K nsproxy                
  5880   5880 100%    0.19K    140       42      1120K proc_dir_entry         
  5201   5149  99%    5.88K   1045        5     33440K task_struct            
  4689   4689 100%    1.31K    198       24      6336K UDPv6                  
  4131   4131 100%    0.08K     81       51       324K Acpi-State             
  4080   4080 100%    0.05K     48       85       192K jbd2_journal_handle    
  3264   3264 100%    0.04K     32      102       128K ext4_system_zone       
  2705   2705 100%    2.19K    196       14      6272K TCP                    
  2544   2544 100%    0.30K     48       53       768K request_sock_TCP       
  2499   2499 100%    0.62K     49       51      1568K task_group             
  2392   2392 100%    0.09K     52       46       208K trace_event_file       
  2256   2256 100%    0.34K     48       47       768K taskstats              
  1872   1872 100%    0.10K     48       39       192K Acpi-ParseExt          
  1776   1776 100%    0.43K     48       37       768K uts_namespace          
  1776   1776 100%    0.21K     48       37       384K file_lock_cache        
  1584   1584 100%    0.24K     48       33       384K tw_sock_TCP            
  1584   1584 100%    0.24K     48       33       384K tw_sock_TCPv6          
  1568   1568 100%    0.12K     49       32       196K uid_cache              
  1536   1536 100%    1.00K     48       32      1536K biovec-64              
  1536   1536 100%    0.12K     48       32       192K ext4_allocation_context
  1418   1418 100%    2.00K     93       16      2976K biovec-128             
  1346   1320  98%    4.00K    170        8      5440K biovec-max             
  1002   1002 100%    2.38K     78       13      2496K TCPv6                  
   928    928 100%    1.00K     29       32       928K RAW                    
   901    901 100%    8.00K    226        4      7232K kmalloc-8k             
   858    858 100%    0.81K     22       39       704K bdev_cache             
   840    840 100%    0.19K     20       42       160K kmalloc-rcl-192        
   754    754 100%    1.19K     29       26       928K RAWv6                  
   627    600  95%    4.00K    137        8      4384K names_cache            
   512    512 100%    0.02K      2      256         8K jbd2_revoke_table_s    
   216    216 100%    0.11K      6       36        24K khugepaged_mm_slot     
   150    150 100%    2.05K     10       15       320K request_queue          
   133    133 100%    4.81K     23        6       736K net_namespace          
   102    102 100%    0.62K      2       51        64K hugetlbfs_inode_cache  
    84     84 100%    0.75K      2       42        64K dax_cache              
    80     80 100%    0.20K      2       40        16K ip4-frags              
    62     62 100%    0.26K      2       31        16K numa_policy            
    53     53 100%    0.30K      1       53        16K request_sock_TCPv6     
    44     44 100%    8.00K     11        4       352K irq_remap_cache        
    40     40 100%    4.00K      5        8       160K kmalloc-rcl-4k         
    34     34 100%    0.94K      1       34        32K mqueue_inode_cache     
    30     30 100%    1.06K      1       30        32K dmaengine-unmap-128    
    30     30 100%    0.52K      1       30        16K user_namespace         
    15     15 100%    2.06K      1       15        32K dmaengine-unmap-256    
     0      0   0%    0.01K      0      512         0K kmalloc-rcl-8          
     0      0   0%    0.02K      0      256         0K kmalloc-rcl-16         
     0      0   0%    0.03K      0      128         0K kmalloc-rcl-32         
     0      0   0%    0.25K      0       32         0K kmalloc-rcl-256        
     0      0   0%    0.50K      0       32         0K kmalloc-rcl-512        
     0      0   0%    1.00K      0       32         0K kmalloc-rcl-1k         
     0      0   0%    2.00K      0       16         0K kmalloc-rcl-2k         
     0      0   0%    8.00K      0        4         0K kmalloc-rcl-8k         
     0      0   0%    0.09K      0       42         0K dma-kmalloc-96         
     0      0   0%    0.19K      0       42         0K dma-kmalloc-192        
     0      0   0%    0.01K      0      512         0K dma-kmalloc-8          
     0      0   0%    0.02K      0      256         0K dma-kmalloc-16         
     0      0   0%    0.03K      0      128         0K dma-kmalloc-32         
     0      0   0%    0.06K      0       64         0K dma-kmalloc-64         
     0      0   0%    0.12K      0       32         0K dma-kmalloc-128        
     0      0   0%    0.25K      0       32         0K dma-kmalloc-256        
     0      0   0%    0.50K      0       32         0K dma-kmalloc-512        
     0      0   0%    1.00K      0       32         0K dma-kmalloc-1k         
     0      0   0%    2.00K      0       16         0K dma-kmalloc-2k         
     0      0   0%    4.00K      0        8         0K dma-kmalloc-4k         
     0      0   0%    8.00K      0        4         0K dma-kmalloc-8k         
     0      0   0%    0.12K      0       34         0K iint_cache             
     0      0   0%    0.69K      0       46         0K xfrm_state             
     0      0   0%    0.20K      0       39         0K pid_namespace          
     0      0   0%    0.03K      0      128         0K dnotify_struct         
     0      0   0%    0.19K      0       42         0K userfaultfd_ctx_cache  
     0      0   0%    0.04K      0      102         0K fat_cache              
     0      0   0%    0.73K      0       44         0K fat_inode_cache        
     0      0   0%    0.81K      0       39         0K ecryptfs_auth_tok_list_item
     0      0   0%    0.02K      0      256         0K ecryptfs_file_cache    
     0      0   0%    1.00K      0       32         0K ecryptfs_inode_cache   
     0      0   0%    0.56K      0       28         0K ecryptfs_key_record_cache
     0      0   0%    0.81K      0       39         0K fuse_inode             
     0      0   0%    0.14K      0       28         0K fuse_request           
     0      0   0%    2.57K      0       12         0K dm_uevent              
     0      0   0%    3.23K      0        9         0K kcopyd_job             
     0      0   0%    1.19K      0       26         0K PINGv6                 
     0      0   0%    0.18K      0       44         0K ip6-frags              
     0      0   0%    0.24K      0       33         0K fsverity_info          
     0      0   0%    1.14K      0       28         0K btrfs_inode            
     0      0   0%    0.41K      0       39         0K btrfs_ordered_extent   
     0      0   0%    0.30K      0       52         0K btrfs_delayed_node     
     0      0   0%    4.06K      0        7         0K x86_fpu                
     0      0   0%    0.16K      0       48         0K kvm_mmu_page_header    
     0      0   0%   15.14K      0        2         0K kvm_vcpu               
     0      0   0%    0.13K      0       30         0K kvm_async_pf           
     0      0   0%    0.22K      0       36         0K xfs_btree_cur          
     0      0   0%    0.47K      0       34         0K xfs_da_state           
     0      0   0%    0.23K      0       35         0K xfs_trans              
     0      0   0%    0.27K      0       30         0K xfs_buf_item           
     0      0   0%    0.43K      0       37         0K xfs_efd_item           
     0      0   0%    1.00K      0       32         0K xfs_inode              
     0      0   0%    0.17K      0       46         0K xfs_rud_item           
     0      0   0%    0.68K      0       47         0K xfs_rui_item           
     0      0   0%    0.38K      0       42         0K xfs_buf                
     0      0   0%    0.48K      0       33         0K xfs_dquot              
     0      0   0%    0.52K      0       31         0K xfs_dqtrx              
     0      0   0%    1.25K      0       25         0K jfs_ip                 
     0      0   0%    0.29K      0       55         0K ntfs_inode_cache       
     0      0   0%    0.94K      0       34         0K ntfs_big_inode_cache   
     0      0   0%    0.66K      0       48         0K minix_inode_cache      
     0      0   0%    0.81K      0       39         0K hfs_inode_cache        
     0      0   0%    0.88K      0       36         0K hfsplus_icache         
     0      0   0%    3.75K      0        8         0K hfsplus_attr_cache     
     0      0   0%    0.66K      0       48         0K qnx4_inode_cache       
     0      0   0%    0.79K      0       40         0K ufs_inode_cache  
```
</details>

<details>
  <summary>Output for only kmalloc items</summary>

```  
165888 165888 100%    0.03K   1296      128      5184K kmalloc-32             
118336 116782  98%    0.06K   1849       64      7396K kmalloc-64             
115712 115712 100%    0.01K    226      512       904K kmalloc-8              
 87552  87552 100%    0.02K    342      256      1368K kmalloc-16             
 72448  62988  86%    0.06K   1132       64      4528K kmalloc-rcl-64         
 54416  54416 100%    0.50K   1723       32     27568K kmalloc-512            
 52084  51748  99%    2.00K   3257       16    104224K kmalloc-2k             
 40047  40047 100%    0.19K    954       42      7632K kmalloc-192            
 33988  33755  99%    1.00K   1077       32     34464K kmalloc-1k             
 32802  32802 100%    0.09K    781       42      3124K kmalloc-96             
 22784  22784 100%    0.12K    712       32      2848K kmalloc-128            
 22008  20544  93%    0.09K    524       42      2096K kmalloc-rcl-96         
  8346   8293  99%    4.00K   1073        8     34336K kmalloc-4k             
  7712   7712 100%    0.25K    241       32      1928K kmalloc-256            
  6816   6539  95%    0.12K    213       32       852K kmalloc-rcl-128        
   901    901 100%    8.00K    226        4      7232K kmalloc-8k             
   840    840 100%    0.19K     20       42       160K kmalloc-rcl-192        
    40     40 100%    4.00K      5        8       160K kmalloc-rcl-4k         
     0      0   0%    0.01K      0      512         0K kmalloc-rcl-8          
     0      0   0%    0.02K      0      256         0K kmalloc-rcl-16         
     0      0   0%    0.03K      0      128         0K kmalloc-rcl-32         
     0      0   0%    0.25K      0       32         0K kmalloc-rcl-256        
     0      0   0%    0.50K      0       32         0K kmalloc-rcl-512        
     0      0   0%    1.00K      0       32         0K kmalloc-rcl-1k         
     0      0   0%    2.00K      0       16         0K kmalloc-rcl-2k         
     0      0   0%    8.00K      0        4         0K kmalloc-rcl-8k    
```
</details>

**Comment by jeffwashington** [comment] 2023-09-07 14:15
you can change the # of bins (and thus, the number of files written) with this constant. It doesn't affect the calculated result and remains compatible with the network.
https://github.com/solana-labs/solana/blob/528a03f32af9f93187d38b1fadde923b55568321/accounts-db/src/accounts_db.rs#L128-L130C4

On pop-net/kin high account count simulation, we have this set at:
`pub const PUBKEY_BINS_FOR_CALCULATING_HASHES: usize = 262144;`

**Comment by HaoranYi** [comment] 2023-09-07 14:22
@steviez Thanks! Yeah. The slab cache usage is high. https://github.com/solana-labs/solana/pull/33178 should help to reduce the active slab objects hold by the writer.

re @jeffwashington yeah. reduce the number of bins or the buffer size will helps too.

re @brooksprumo I think the oom-killer didn't track that slab cache is full. I don't think slab cache size can be configured. It is managed by the allocator of the kernel.

**Comment by HaoranYi** [comment] 2023-09-07 14:36
I think if we increase the number of pubkeybin and the buffer size, we will have a higher chance of reproduce this failure.

**Comment by jeffwashington** [comment] 2023-09-07 14:37
> I think if we increase the number of pubkeybin and the buffer size, we will have a higher chance of reproduce this failure.

I can definitely experiment with this. Let's see, what's the max power of 2 that fits in a u64... Ha.  I'll run some of these.

**Comment by jeffwashington** [comment] 2023-09-07 15:00
524,288 bins and `BufWriter::with_capacity(256_000,` ran successfully on ledger tool, where the hash calc occurred twice.
I started a mnb validator with these settings.

**Comment by jeffwashington** [comment] 2023-09-07 15:21
so far 2 validators are running successfully with these amped up settings and calculating the hash every 50s or so. About 20 successful hash calcs so far.

**Comment by steviez** [comment] 2023-09-20 19:17
Double checked with @jeffwashington - given https://github.com/solana-labs/solana/pull/33195 and its' PR, closing this one out. Can reopen if we discover that it wasn't properly fixed

**Closed by steviez** 2023-09-20 19:17 UTC
