### ISSUE TITLE
RPC: getConfirmedSignaturesForAddress2 times out for low activity accounts

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11479] opened 2020-08-09 05:16 UTC
#### Problem
When searching for account tx history on an account without many associated transactions, the request will always timeout on Mainnet RPC. This happens when the `limit` is higher than the total available transactions, causing a full slot scan for transaction history

#### Proposed Solution
- Rework rocksdb CF's
- Limit API node ledger history to 3-4 epochs

**Comment by jstarry** [comment] 2020-08-09 05:16
cc @mvines

**Comment by mvines** [comment] 2020-08-09 05:21
> Index transactions by address?

Reworking the rocksdb CFs is the best way forward, the BigTable scheme can be used as a template for what we need.  My initial implementation of getConfirmedSignaturesForAddress2 intentionally didn't rework the CFs since I didn't want to add in that complexity at the time.

An non-code option that will help regardless is to reduce the rocksdb ledger history on all the API nodes.  Data uploads to BigTable at the start of each new epoch, so API nodes really just need to store 3-4 epochs of data now.   This'll help the current poor code terminate faster and overall help with rocksdb performance.

**Comment by jstarry** [comment] 2020-08-09 05:24
I see, so the slowness is mostly coming from the initial rocksdb scan, _not_ BigTable?

**Comment by mvines** [comment] 2020-08-09 05:25
> I see, so the slowness is mostly coming from the initial rocksdb scan, _not_ BigTable?

Yep, 100%.  BigTable is super fast.  You can actually issue BigTable queries directly using `solana-ledger-tool bigtable ...`

**Comment by CriesofCarrots** [comment] 2020-08-09 06:07
Isn't https://github.com/solana-labs/solana/pull/11426 a fix for this particular issue?

**Comment by CriesofCarrots** [comment] 2020-08-09 06:13
To be clear, we still need to rework rocks column families to prevent this issue on accounts that have low-activity, some of which was many slots in the past.

**Comment by mvines** [comment] 2020-08-09 06:17
> Looks like it hasn't made it into a 1.2 release yet, so presumably isn't on the MNB api nodes

I'll update the MB api nodes tomorrow evening with the latest from the v1.2 branch once https://github.com/solana-labs/solana/pull/11480 merges

**Comment by CriesofCarrots** [comment] 2020-08-09 06:29
... actually, I think we might be able to optimize `getConfirmedSignaturesForAddress2` further to prevent this issue entirely, so the need to rework the CF would be to present signatures in proper time order. I'll give it a go on Monday.

**Comment by jstarry** [comment] 2020-08-09 07:13
FYI #11480 is missing an important piece (fallback when json parsing fails), I'd like to get that in as well. Will add y'all to the review

**Closed** 2020-08-10 16:27 UTC
