### ISSUE TITLE
RPC node's send_transaction() doesn't retry

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9974] opened 2020-05-11 15:42 UTC
#### Problem

Same problem as #9400, but creating a separate ticket with reduced scope.

#### Proposed Solution

Add a thread to the RPC node that resends transactions until its blockhash expires.

**Comment by mvines** [comment] 2020-05-11 15:45
Duplicate of https://github.com/solana-labs/solana/issues/9401

**Comment by garious** [comment] 2020-05-11 15:47
Not a duplicate.  `RpcClient::send_transaction()` should remain non-blocking.

**Comment by aeyakovenko** [comment] 2020-05-30 03:28
While the RPC node is retrying, the leader should make a best effort to send back the signature + status code to the RPC node if the transaction failed in such a way that it won't be encoded into the ledger.

**Comment by mvines** [comment] 2020-06-06 18:43
> While the RPC node is retrying, the leader should make a best effort to send back the signature + status code to the RPC node if the transaction failed in such a way that it won't be encoded into the ledger.

The new sendTransaction preflight checks should mitigate most of this concern, as they will filter out invalid transactions and most execution errors.

**Closed** 2020-06-09 14:46 UTC
