### ISSUE TITLE
Validator Node WARNings after testnet network reset

### ISSUE THREAD

**Issue by sunnya97** [solana-labs/solana#4842] opened 2019-06-27 01:38 UTC
#### Problem

After the testnet network reset at approx 1:15am UTC on June 27, 2019, our node process running `validator.sh` started repeatedly spitting out an error with an occasional leader update message.  A short clip of our log message is as below:
```
...
[2019-06-27T01:33:31.595368186Z WARN  solana::cluster_info_repair_listener] Root for repairee is on different fork OR replay_stage hasn't marked this slot as root yet
[2019-06-27T01:33:31.595393114Z WARN  solana::cluster_info_repair_listener] Root for repairee is on different fork OR replay_stage hasn't marked this slot as root yet
[2019-06-27T01:33:31.769792980Z WARN  solana::cluster_info] 7PK3ghCbnEpcZQ4VSYaveJ7BtuCfBQB4Vw4nyu5oWmi: LEADER_UPDATE TO FHwYf4t7wN5opFb5qQtTSXHFdJGLE5J9LtWMMsEBKvDX from 5HeDBepxmuouZCWkQYAWuiurv4Rq8jN6BmF54N4fQyBq
[2019-06-27T01:33:31.795828916Z WARN  solana::cluster_info_repair_listener] Root for repairee is on different fork OR replay_stage hasn't marked this slot as root yet
[2019-06-27T01:33:31.795877336Z WARN  solana::cluster_info_repair_listener] Root for repairee is on different fork OR replay_stage hasn't marked this slot as root yet
...
```
The node was built from source and a restart of the node does not resolve the error.

The output of `show-vote-account` shows our account of having 0 credits.

```
$ solana-wallet show-vote-account DFMgEgYrER3GtLnwr7ye7DkD7qzZU6hoKWTs9mPZzGBk
account lamports: 1
node id: 7PK3ghCbnEpcZQ4VSYaveJ7BtuCfBQB4Vw4nyu5oWmi
authorized voter pubkey: DFMgEgYrER3GtLnwr7ye7DkD7qzZU6hoKWTs9mPZzGBk
credits: 0
commission: 0.000015258556235409006%
root slot: ~
```

**Comment by mvines** [comment] 2019-06-27 04:52
Thank you for this report @sunnya97.  This is a duplicate of #4817, which is a known issue for the 0.16.0.  We're working on it :)

**Closed by mvines** 2019-06-27 04:52 UTC
