### ISSUE TITLE
Intermittent ci test failure - `test_quic_server_multiple_writes`

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#29581] opened 2023-01-09 15:17 UTC
#### Problem

```
<html>
<body>
<!--StartFragment-->

[2023-01-08T16:38:50.078086000Z TRACE solana_streamer::nonblocking::quic] sent 1 byte packet
--
  | thread 'quic::test::test_quic_server_multiple_writes' panicked at 'called `Result::unwrap()` on an `Err` value: Stopped(0)', streamer/src/nonblocking/quic.rs:1155:27
  | stack backtrace:
  | 0: rust_begin_unwind
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/panicking.rs:575:5
  | 1: core::panicking::panic_fmt
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/panicking.rs:65:14
  | 2: core::result::unwrap_failed
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/result.rs:1791:5
  | 3: core::result::Result<T,E>::unwrap
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/result.rs:1113:23
  | 4: solana_streamer::nonblocking::quic::test::check_multiple_writes::{{closure}}
  | at ./src/nonblocking/quic.rs:1155:9
  | 5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/future/mod.rs:91:19
  | 6: tokio::park::thread::CachedParkThread::block_on::{{closure}}
  | at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/park/thread.rs:263:54
  | 7: tokio::coop::with_budget::{{closure}}
  | at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/coop.rs:106:9
  | 8: std::thread::local::LocalKey<T>::try_with
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/thread/local.rs:446:16
  | 9: std::thread::local::LocalKey<T>::with
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/std/src/thread/local.rs:422:9
  | 10: tokio::coop::with_budget
  | at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/coop.rs:99:5
  | 11: tokio::coop::budget
  | at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/coop.rs:76:5
  | 12: tokio::park::thread::CachedParkThread::block_on
  | at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/park/thread.rs:263:31
  | 13: tokio::runtime::enter::Enter::block_on
  | at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/enter.rs:151:13
  | 14: tokio::runtime::thread_pool::ThreadPool::block_on
  | at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/thread_pool/mod.rs:77:9
  | 15: tokio::runtime::Runtime::block_on
  | at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/mod.rs:463:43
  | 16: solana_streamer::quic::test::test_quic_server_multiple_writes
  | at ./src/quic.rs:449:9
  | 17: solana_streamer::quic::test::test_quic_server_multiple_writes::{{closure}}
  | at ./src/quic.rs:444:5
  | 18: core::ops::function::FnOnce::call_once
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/ops/function.rs:251:5
  | 19: core::ops::function::FnOnce::call_once
  | at /rustc/11ebe6512b4c77633c59f8dcdd421df3b79d1a9f/library/core/src/ops/function.rs:251:5
  | note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  | [2023-01-08T16:38:50.190019271Z DEBUG solana_streamer::nonblocking::quic] stream error: ApplicationClosed(ApplicationC

<!--EndFragment-->
</body>
</html>

#### Proposed Solution

**Comment by steviez** [comment] 2023-01-09 18:26
This looks like the same issue as https://github.com/solana-labs/solana/issues/29096; I see you have an open PR and haven't looked at that yet, but if it does fix the issue, I think we can close the issue I linked as well

**Comment by steviez** [comment] 2023-01-10 22:28
Closing this issue as it is a duplicate of: https://github.com/solana-labs/solana/issues/29096

**Closed by steviez** 2023-01-10 22:28 UTC
