### ISSUE TITLE
Solana SPL token transfer transactions are not visible when searching by receiving wallet address

### ISSUE THREAD

**Issue by lexer** [solana-labs/solana#27631] opened 2022-09-07 02:08 UTC
#### Problem

Solana SPL token transfer transactions are not visible when searching by receiving wallet address

Transaction example:

Here is my USDC transfer from Coinbase -> Wallet (GXwCSk2RPHDFHPzBSo42CSKU1D94FNoo6qpbZFQG8TfK
): https://solscan.io/tx/KoF3F4mehdGoUEUbN97jHu9dR79ifiTb52hT5nT2NGuLt4Qe4eUFNvyGRZXW5fmhq5LowMP6FsNjor1qtUJmroc

The problem is that this transaction is not visible if I will try to query transactions by my wallet:
https://solscan.io/account/GXwCSk2RPHDFHPzBSo42CSKU1D94FNoo6qpbZFQG8TfK

It is only visible if I will look into my wallet's USDC associated token account: 
https://solscan.io/account/DZRyJk81qfGRzdVfBPQPmCKmYkuEAsaX6RHvQDcKUR1R

#### Proposed Solution

Maybe SDK should automatically add receiver as extra key to transfer instruction?

instruction = createTransferCheckedInstruction(
  senderATA,
  splToken,
  recipientATA,
  sender,
  sendAmount,
  mint.decimals,
);

// This is essential for transaction to be searchable by recipient wallet
instruction.keys.push({
  pubkey: recipient,
  isWritable: false,
  isSigner: false,
});

**Comment by joncinque** [comment] 2022-09-12 21:15
This is a dupe of https://github.com/solana-labs/solana-program-library/issues/1891 -- feel free to keep up there.  There hasn't been much movement on it though.

**Closed by joncinque** 2022-09-12 21:15 UTC
Labels: community
