### ISSUE TITLE
Confusing Function "getInflationReward"

### ISSUE THREAD

**Issue by icepaq** [solana-labs/solana#22964] opened 2022-02-05 17:00 UTC
#### Problem
Recently I had spent a few hours trying to figure out how to get the staking rewards for an account. After a few hours, I had thought of looking at the Solana explorer's code to understand how it's done. 

I'm sure I'm not the only person who has gotten stuck on this as I was unable to get a clear answer from the discord help channel.

#### Proposed Solution
Creating a new API route is probably not worth it but updating the docs would be sufficient.

The current description for `getInflationReward` is `Returns the inflation reward for a list of addresses for an epoch`. Adding something that would let the user know this is used for getting stake rewards would be helpful.

**Comment by steviez** [comment] 2022-02-06 17:30
Duplicate of https://github.com/solana-labs/solana/issues/22963

**Closed by steviez** 2022-02-06 17:30 UTC
