### ISSUE TITLE
Failed to open ledger database: UnableToSetOpenFileDescriptorLimit

### ISSUE THREAD

**Issue by GooSatoru** [solana-labs/solana#19603] opened 2021-09-03 02:44 UTC
Run a validator node got error bellow

```
thread 'main' panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   3: solana_core::validator::new_banks_from_ledger
   4: solana_core::validator::Validator::new
   5: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-09-03T02:37:36.447526344Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Failed to open ledger database: UnableToSetOpenFileDescriptorLimit', core/src/validator.rs:1080:6" location="core/src/validator.rs:1080:6"


```

**Comment by onurplusplus** [comment] 2021-09-03 06:04
Duplicate of [#19575](https://github.com/solana-labs/solana/issues/19575)

**Comment by t-nelson** [comment] 2021-09-03 21:09
> Duplicate of #19575

this

**Closed by t-nelson** 2021-09-03 21:09 UTC
