### ISSUE TITLE
Can't start solana-test-validator

### ISSUE THREAD

**Issue by bezrazli4n0** [solana-labs/solana#28899] opened 2022-11-20 21:38 UTC
#### Problem

Trying to start `solana-test-validator`, but it closes unexpectedly without meaningful errors.

- Logs:
```
[2022-11-20T20:56:59.883887000Z INFO  solana_test_validator] solana-validator 1.15.0 (src:devbuild; feat:3018528013)
[2022-11-20T20:56:59.884074000Z INFO  solana_test_validator] Starting validator with: ArgsOs {
        inner: [
            "/Users/cat/Desktop/solana/target/debug/solana-test-validator",
        ],
    }
[2022-11-20T20:56:59.884274000Z WARN  solana_perf] CUDA is disabled
[2022-11-20T20:56:59.892855000Z INFO  solana_faucet::faucet] Faucet started. Listening on: 0.0.0.0:9900
[2022-11-20T20:56:59.892912000Z INFO  solana_faucet::faucet] Faucet account address: J5JBJhxPtam1DMFutGZiRAaBU2ovBPe2gvo7GbqgXtyr
[2022-11-20T20:56:59.903481000Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 1000000
[2022-11-20T20:56:59.903523000Z INFO  solana_ledger::blockstore] Opening database at "test-ledger/rocksdb"
[2022-11-20T20:57:00.131711000Z INFO  solana_ledger::blockstore] "test-ledger/rocksdb" open took 228ms
[2022-11-20T20:57:00.176898000Z INFO  solana_metrics::metrics] metrics disabled: SOLANA_METRICS_CONFIG: environment variable not found
[2022-11-20T20:57:00.177048000Z INFO  solana_metrics::metrics] datapoint: shred_insert_is_full total_time_ms=0i slot=0i last_index=3i num_repaired=0i num_recovered=0i
[2022-11-20T20:57:00.223536000Z INFO  solana_runtime::hardened_unpack] Extracting "test-ledger/genesis.tar.bz2"...
```

- Error:
```
Error: failed to start validator: Failed to create ledger at test-ledger: blockstore error
```
- OS: macOS 13.0.1
- CPU: Apple M1 Pro
- bzip2: 1.0.8
- solana-test-validator: 1.13.6(also tried from latest master-commit)

**Comment by steviez** [comment] 2022-11-21 17:19
This is a duplicate of:
https://solana.stackexchange.com/questions/4258/getting-error-when-running-solana-test-validator

**Closed by steviez** 2022-11-21 17:19 UTC
Labels: community

**Comment by KirillLykov** [comment] 2022-11-21 17:59
@bezrazli4n0 could you post your question to stackexchange (with all the versions etc) because original post is missing this information. On mac 12.2 I could not reproduce (`./validator/solana-test-validator`)

**Comment by bezrazli4n0** [comment] 2022-11-21 23:32
Moved to [solana stackexchange](https://solana.stackexchange.com/questions/4499/cant-start-solana-test-validator).
System reboot with `test_ledger` deletion doesn't work in my case :(

@KirillLykov @steviez

**Comment by bezrazli4n0** [comment] 2022-12-14 10:26
The problem was that macOS 13 had the wrong version of tar installed. You need to replace it with the homebrew version of gnu. Detailed instructions provided on [stackexchange](https://solana.stackexchange.com/a/4761/2844).

**Comment by fitzlee** [comment] 2023-08-26 04:13
brew install gnu-tar
/usr/local/Cellar/gnu-tar/1.35/bin/gtar

brew install gnu-tar
# Put this in ~/.zshrc 
export PATH="/usr/local/Cellar/gnu-tar/1.35/bin/:$PATH"

$ which tar, do replace system tar
cd /usr/local/Cellar/gnu-tar/1.35/bin/
cp gtar tar

**Comment by RdeWilde** [comment] 2023-12-06 20:45
Might also related with the tar copyfiles issue as fixed here: https://github.com/solana-labs/solana/pull/34176
