### ISSUE TITLE
Make LOG_MESSAGES_BYTES_LIMIT configurable

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#25515] opened 2022-05-24 11:36 UTC
#### Problem

Currently LOG_MESSAGES_BYTES_LIMIT is hard-coded to `10 * 1000`. When you surpass this limit, your program logs will stop being populated and will just say `Log truncated`.

I assume this limit needs to be there, but right now it's pretty easy to hit, especially when chaining instructions together.

#### Proposed Solution

- It should at least be possible to configure `solana-test-validator` to run with a higher limit.
- Perhaps the default limit should be increased.
- I don't know if there are any extra considerations involved in making the limit configurable for mainnet RPCs, but it seems like it would be nice to have.

**Comment by paul-schaaf** [comment] 2022-05-24 12:05
related https://github.com/solana-labs/solana/issues/23653

**Comment by CriesofCarrots** [comment] 2022-05-24 16:10
I'm closing this as a duplicate of #22301, but thanks for bringing up the consideration of `solana-test-validator` vs full RPC node

**Closed by CriesofCarrots** 2022-05-24 16:10 UTC
