### ISSUE TITLE
Docker `stable` tag doesn't build

### ISSUE THREAD

**Issue by samuelvanderwaal** [solana-labs/solana#20514] opened 2021-10-07 17:29 UTC
#### Problem
The latest Docker `stable` image doesn't build.
Digest hash: `196dc7a929f45536547970baadfcc27971363d8c06b00f8c4227476221801b6c`

```
# docker-compose.yml
version: '3'

services:
    solana:
        image: solanalabs/solana:stable
        ports:
            - 8899:8899
            - 8900:8900
```

Run `docker-compose up`.

Error: `/usr/bin/solana-run.sh: line 66: ./fetch-spl.sh: No such file or directory`

**Comment by steviez** [comment] 2021-10-08 22:59
Hi @samuelvanderwaal - thanks for the bug report; we are aware of the issue and working on pushing the fix through. Just incase you're playing around with multiple versions, the issue is present in `beta` (v1.8) as well

I'll close this issue out once the issue has been resolved. However, if you're blocked in the short term, I'd recommend one of:
- Using [v1.7.12](https://hub.docker.com/layers/solanalabs/solana/v1.7.12/images/sha256-233515a3736a564953d5cbf8a37b7fae7ba7ed66a93270ecfd63a4a71da873ba?context=explore) temporarily (`stable is currently against v1.7 branch); `v1.7.12` is the last tag that doesn't have the issue
- Apply the changes in https://github.com/solana-labs/solana/pull/19932

**Closed as completed** 2021-10-13 01:52 UTC
Labels: locked issue
