### ISSUE TITLE
warp_to_slot function in solana_program_test doesn't update time properly with large slot warps

### ISSUE THREAD

**Issue by rusted-ruby** [solana-labs/solana#24867] opened 2022-04-30 17:12 UTC
#### Problem
`warp_to_slot` in `solana_program_test` has some odd behavior when warping. I've noticed the following while writing integration tests for my time-based programs. Here is a brief snippet of my code.
```rust
  pub async fn fast_forward(&mut self, next_ts: i64, slot_increment: u64) {
    let mut clock = self.get_clock().await;
    while clock.unix_timestamp <= next_ts {
      self.context.warp_to_slot(clock.slot + slot_increment).unwrap();
      clock = self.context
        .banks_client
        .get_sysvar::<Clock>()
        .await
        .unwrap();
      println!("clock ts: {} and clock slot: {}", clock.unix_timestamp, clock.slot);
    }
  }
```
I've noticed the following while using this `fast_forward` function to warp ahead by two weeks (roughly 1.2 million seconds).
* warping in large slot increments does not work as expected. The slot on the resultant `Clock` object updates, but the `unix_timestamp` does not. So, say our initial `Clock` object has a slot of 1 and a unix timestamp of `1651336913`. Setting `slot_increments` to 500_000 will yield a `Clock` object with a slot of 500_001 and a unix timestamp of `1651336913` after the first iteration of the `while` loop. This results in an infinite loop and prevents the `fast_forward` function from working.
* Warping in smaller slot increments works better, but smaller slot increments allow you to progress further in unix time. After a certain unix timestamp, we see the same problem as above: the slot of the resultant `Clock` object continues to update, but the `unix_timestamp` does not. For example, setting `slot_increments` to 400 allows me to move about 300k seconds forward in unix time before I'm caught in an infinite loop. Setting it to 200 allows me to move about 600k seconds forward and setting it to 100 allows me to move the 1.2 million seconds forward I need to pass the two week mark for my test. 

So it seems that for users who wish to fast forward large portions of time in their tests, smaller slot increments is the way to go. However, this means tests take significantly longer to run. It would be nice if we could warp forward in time in larger leaps and bounds.

**Comment by t-nelson** [comment] 2022-04-30 19:30
duplicate of https://github.com/solana-labs/solana/issues/19822

**Closed by t-nelson** 2022-04-30 19:30 UTC

**Comment by oeble** [comment] 2023-10-28 23:39
For anyone reading this and searching for a solution, `set_sysvar` is actually a better option than `warp_to_slot`.
