### ISSUE TITLE
Staking reward return zero

### ISSUE THREAD

**Issue by WinterValidator** [solana-labs/solana#24421] opened 2022-04-16 23:34 UTC
#### Problem
My node run fine but no staking reward return during some epoch. 
After I have resolved error with solana witthdraw-from-vote account.  by re-created vote account and it run fine during 3 epoch to now.
Staking account show that last staking reward is epoch 296: https://solanabeach.io/address/7wcvrxVodTrmKTL4KEdbbDzwgQ5y1zLpBciMMY31NRkB/stake-rewards

**Comment by CriesofCarrots** [comment] 2022-04-17 23:09
Hi, @WinterValidator . If you fully withdrew your vote account, unfortunately what you describe is a known issue, tracked here: https://github.com/solana-labs/solana/issues/22512

Once your newly accrued credits exceed those you had accrued before nuking your account, you will start receiving staking rewards. In the meantime, your only alternative to waiting is to have your delegators deactivate and then re-delegate their stake.
I am not sure if you are in the Foundation delegation program or not, but the Foundation has been willing to do this operation in the past.

This change https://github.com/solana-labs/solana/pull/22546 would jump start your rewards without delegators having to do anything, but it would need to be merged and the feature activated.

**Comment by CriesofCarrots** [comment] 2022-04-23 16:08
If you don't have any further questions, I'm closing this issue as a duplicate of #22512

**Closed by CriesofCarrots** 2022-04-23 16:08 UTC
