### ISSUE TITLE
Transaction.populate() Creates a message with accounts in unexpected order

### ISSUE THREAD

**Issue by billyjacoby** [solana-labs/solana#23610] opened 2022-03-11 14:03 UTC
#### Problem
When creating a transaction from a base58 encoded message using the `Transaction.populate()` function, the order of the `accountKeys` does not match the order of the `accountKeys` the original message. The account keys are all the same, but them being in a different order is causing issues. 

This is leading to a signature verification failure, even though the two transactions technically have the same information in them.

I have created a repository that replicates this issue, and includes JSON outputs of the message before and after being passed in to the `Transaction.populate()` method. 

The repo can be found [here.](https://github.com/billyjacoby/solana-signature-problem)

#### Proposed Solution
Figure out how to have the `Transaction.populate()` function return a message that has the `accountKeys` in the same order as the message it is constructed from.

**Comment by t-nelson** [comment] 2022-03-11 16:41
duplicate of https://github.com/solana-labs/solana/issues/21722 (from calls populate)

**Closed by t-nelson** 2022-03-11 16:41 UTC
