### ISSUE TITLE
Allow cargo args for build-bpf

### ISSUE THREAD

**Issue by dhyon** [solana-labs/solana#19707] opened 2021-09-08 04:33 UTC
#### Problem
`cargo build-spf` places tremendous memory pressure on my 16gb macos machine. I want to specify `--jobs 1` and pass it through this cmd. I think this arg has the right idea but I don't know how to invoke it: https://github.com/solana-labs/solana/blob/89a31ff473470513e3855edaa1c73cdedef0643d/sdk/cargo-build-bpf/src/main.rs#L674

Adding --cargo_args to the cargo build-spf command doesn't work.

#### Proposed Solution

Please enable pass through of cargo args.

**Comment by dmakarov** [comment] 2021-09-08 19:19
cargo_args is a last argument. it means that it is not named, but instead `--` is treated as the start of multiple arguments passed to cargo build directly, e.g. `-- --jobs 1` at the end of the command line should have the effect of passing `--jobs 1` to `cargo build`.

**Comment by dmakarov** [comment] 2021-09-08 19:26
This is also explained in the only help
```
$ cargo-build-bpf --help
solana-cargo-build-bpf 1.8.0
Compile a local package and all of its dependencies using the Solana BPF SDK

USAGE:
    cargo-build-bpf [FLAGS] [OPTIONS] [-- <cargo_args>...]

FLAGS:
        --dump                                Dump ELF information to a text file on success
        --generate-child-script-on-failure    Generate a shell script to rerun a failed subcommand
    -h, --help                                Prints help information
        --no-default-features                 Do not activate the `default` feature
        --offline                             Run without accessing the network
    -V, --version                             Prints version information
    -v, --verbose                             Use verbose output
        --workspace                           Build all BPF packages in the workspace

OPTIONS:
        --bpf-out-dir <DIRECTORY>    Place final BPF build artifacts in this directory
        --bpf-sdk <PATH>             Path to the Solana BPF SDK [default:
                                     /Users/dmakarov/.local/share/solana/install/active_release/bin/sdk/bpf]
        --features <FEATURES>...     Space-separated list of features to activate
        --manifest-path <PATH>       Path to Cargo.toml

ARGS:
    <cargo_args>...    Arguments passed directly to `cargo build`
```

I'm going to close this issue. Please, re-open if the issue is something else.

**Closed by dmakarov** 2021-09-08 19:26 UTC
