### ISSUE TITLE
Multi signature transaction breaking change v1.31.0 -> v1.36.0

### ISSUE THREAD

**Issue by NorbertBodziony** [solana-labs/solana#23838] opened 2022-03-22 15:15 UTC
#### Problem
I have noticed that when you want to serialize transaction generated using `v1.31.0` of solana/web3.js using `v1.36.0` we will get error of invalid signature.
Following code works on `v1.31.0` but not on `v1.36.0`

```
  const deSerialized = Transaction.from(
    Buffer.from(
      '02000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005e0ee73ab04c5b8c607c02a35e2c376a4c3e704dea69424fd80e60a19862a3278a29453b2deaaa4ed85def63934bf66ff63fe257c1467d99e5315b98188fd6020201010917c54f4c90947de5c16133c138cda010b750bd9b72907db689047a1dd77f1af4b5c10379d39e7e901b9de5921c2c298028517ee22481f5ded924753337abea037714e573d457a758e61991b995d505930fcb64b905cd3b0926e729494b984a35e821df929b128a198b923b0c2a789390091980eaedb9194d9daf3163da92c7f4b249b543de0179bf4fd326e79cb331279beabae351cc7158fce924bab07385042c5ce7730abf39fec165cfacaf98651c02968856edb42800db5cdfef08aac69bf7e38dfda62f9a02f8711839e305329e182e0b9b1ade833b473e21fb08dc43fbc144c1b6d5352af80d71c920d6bea6eb38258506529bce7099f692540eeb2ad906ddf6e1d765a193d9cbe146ceeb79ac1cb485ed5f5b37913a8cf5857eff00a967aeeffd8858fa031b319bb613094bc622ce29203e157462758bbf07aa471907030803020301090700e1f505000000000803040501090700e1f505000000000803060701090700e1f50500000000',
      'hex'
    )
  )
  console.log(deSerialized.serialize({ requireAllSignatures: false }).toString('hex'))
  ```
  This only affects tx with multiple signers.

#### Proposed Solution
I guess use same package but what about wallets ?

**Comment by t-nelson** [comment] 2022-03-22 17:14
duplicate of https://github.com/solana-labs/solana/issues/21722

**Closed by t-nelson** 2022-03-22 17:14 UTC
