### ISSUE TITLE
Testnet Validator is failing to start 

### ISSUE THREAD

**Issue by anishnath** [solana-labs/solana#26074] opened 2022-06-20 07:20 UTC
#### Problem

Testnet validator is not coming up 

Testnet **v1.10.24**

```
root@solana-testnet-0:/# solana-validator     --identity /etc/solana-secrets/validator-keypair.json     --vote-account /etc/solana-secrets/vote-account-keypair.json     --known-validator 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on     --known-validator dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs     --known-validator Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN     --known-validator eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ     --known-validator 9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv     --only-known-rpc     --ledger ledger     --rpc-port 8899     --dynamic-port-range 8000-8020     --entrypoint entrypoint.testnet.solana.com:8001     --entrypoint entrypoint2.testnet.solana.com:8001     --entrypoint entrypoint3.testnet.solana.com:8001     --expected-genesis-hash 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY     --wal-recovery-mode skip_any_corrupted_record     --limit-ledger-size     --no-incremental-snapshots     --no-os-network-limits-test
```

Error message 

```
[2022-06-20T07:16:23.729405250Z INFO  solana_metrics::metrics] datapoint: memory-stats total=135039213568i swap_total=25165816i free_percent=88.57852684973362 used_bytes=7475527680i avail_percent=94.4641800833388 buffers_percent=1.0828559744711916 cached_percent=4.612455297559571 swap_free_percent=98.48022412625126
thread 'main' panicked at 'Load from snapshot failed: Io(Custom { kind: Other, error: "invalid snapshot data file: /ledger/snapshot/tmp-snapshot-archive-VAJKyk/snapshots/137740010/137740010 has 206649979 bytes, however consumed 206649971 bytes to deserialize" })', ledger/src/bank_forks_utils.rs:233:10
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: solana_ledger::bank_forks_utils::load_bank_forks
   4: solana_core::validator::Validator::new
   5: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2022-06-20T07:16:24.941524637Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Load from snapshot failed: Io(Custom { kind: Other, error: \"invalid snapshot data file: /ledger/snapshot/tmp-snapshot-archive-VAJKyk/snapshots/137740010/137740010 has 206649979 bytes, however consumed 206649971 bytes to deserialize\" })', ledger/src/bank_forks_utils.rs:233:10" location="ledger/src/bank_forks_utils.rs:233:10" version="\"1.10.24 (src:15456493; feat:2982808786)\""
```

Have clean the ledger and retried Multiple times also enable disable `--no-incremental-snapshots` the system is not cming up

**Comment by steviez** [comment] 2022-06-21 18:00
Hi @anishnath - thanks for reporting the issue. I think I know what the issue is; we're in a little bit of a transition period where we've been updating major software versions on our clusters (mainnet 1.9 ==> 1.10 and testnet 1.10 ==> 1.11).

The first known-validator you have listed is: `5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on`. By running solana validators command against testnet, I can see that `5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on` is running v1.11.0 (which isn't released yet). However, you're running a `v1.10` release which is incompatible. So, my guess is that you're getting a snapshot from this node, and the snapshot has an extra field that is causing the deserialize issue.

The quick, temporary solution I'd recommend is to remove `5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on` from your list of known-validators. Additionally, you can double check that the rest of your known validators listed out are running a `v1.10` release by running `solana validators -ut`.

I'd expect the recommended software version for testnet to move to `v1.11` in the next week or two.

**Comment by brooksprumo** [comment] 2022-06-21 18:46
I think this issue may've been caused by a new snapshot field that has not been backported to v1.10 yet. Backport PR#25805 should hopefully fix this issue.

**Comment by steviez** [comment] 2022-06-21 19:35
Awesome, thanks for looking into that @brooksprumo ! @anishnath - in best case scenario, the PR brooksprumo mentioned will land in the next `v1.10` release (`v1.10.27`). In the short term, I'd still recommend trying to adjust your known validator list.

**Comment by AshwinSekar** [comment] 2022-06-22 11:40
Backport was successful, should be fixed in the next release.

**Closed by AshwinSekar** 2022-06-22 11:40 UTC
