### ISSUE TITLE
Validator stalls after few hours on local cluster

### ISSUE THREAD

**Issue by kalilinuxoo7** [solana-labs/solana#26527] opened 2022-07-09 09:24 UTC
@michaelh-laine - Agreed with jstarry that logs before the incident would be nice too. Included in logs before would be this line (forgot to ask for it initially):
```
solana_runtime::bank] accounts hash slot: 131436226 stats {}
```

1) Comparing your bank frozen to our bank frozen, the accounts delta is the differing value while sig_count, last_blockhash, and capitalization all look good.
2) Thanks and confirmed looking over your attached log file; up to the restart (restart @ line 469626), your node has repeated:
```
[2022-04-26T18:11:20.682282171Z INFO  solana_core::replay_stage] Waiting to switch vote to 131436225, resetting to slot Some(131436225) for now, latest duplicate ancestor: 131436226
```
3) Here's the line of what you reloaded with; the incremental snapshot was at `131436908` so yes, it restarted after your trouble spot.
```
[2022-04-26T18:12:37.981700899Z INFO  solana_runtime::snapshot_utils] Loading bank from full snapshot: /mnt/validator/snapshots/snapshot-131415052-2dKYPcfLfWuqCRiUGNYs4fK9MdKnK8qjyFTR3Vn4vokZ.tar.zst, and incremental snapshot: Some("/mnt/validator/snapshots/incremental-snapshot-131415052-131436908-9pBTgaERt1anPqhDVEjLKgd9sg3vHBcE8cja1rsfyuaj.tar.zst")
```
4) Got it, thanks for confirming

_Originally posted by @steviez in https://github.com/solana-labs/solana/issues/24710#issuecomment-1111224704_

#### Problem
I am trying to run a local cluster on AWS instances. After starting the leader node, the second node syncs well too and starts voting.
I am having this same issue. But the node which had this problem was not the leader at that slot.
Logs from bootstrap validator
`[2022-07-09T08:06:18.809154364Z INFO  solana_runtime::bank] bank frozen: 23763397 hash: 7DRDzMaXhuPraZ5PaHnVWrj6uV4JtkwXJtYpzLjGVZzq accounts_delta: 2sgduxEeF3JXfc2aEchKTyvT8dwBDATDsi8b6NaCAw18 signature_count: 3 last_blockhash: 6gfoBG3ZaEHrbXJqW5iJYBdQu12zwjdDw7NfPpoLfsXG capitalization: 2810742211885236
[2022-07-09T08:06:18.809165485Z INFO  solana_runtime::bank] accounts hash slot: 23763397 stats: BankHashStats { num_updated_accounts: 13, num_removed_accounts: 0, num_lamports_stored: 89450146628081, total_data_len: 178727, num_executable_accounts: 0 }`

Logs from second validator
`[2022-07-09T08:06:18.891255909Z INFO  solana_runtime::bank] bank frozen: 23763397 hash: Boj6uxm3NxFeHyzZurrQrDiLMUUe57BXU7pQrDAt7SBD accounts_delta: A6sGRYMNqiTcx5T2beR3o1WfUzJjjsiQFTdyKxYgLmPj signature_count: 3 last_blockhash: 6gfoBG3ZaEHrbXJqW5iJYBdQu12zwjdDw7NfPpoLfsXG capitalization: 2810742211885236
[2022-07-09T08:06:18.891269946Z INFO  solana_runtime::bank] accounts hash slot: 23763397 stats: BankHashStats { num_updated_accounts: 13, num_removed_accounts: 0, num_lamports_stored: 89450146628081, total_data_len: 178727, num_executable_accounts: 0 }`

Then this line keeps repeating
`[2022-07-09T08:06:19.103916897Z INFO  solana_core::replay_stage] Waiting to switch vote to 23763396, resetting to slot Some(23763396) for now, latest duplicate ancestor: 23763397`

Can you please help me with this issue? And please can you refer exactly which commit or PR fixes this issue?

**Comment by steviez** [comment] 2022-07-11 21:45
What software version (or commit if built-from-source) are you using ?

**Comment by kalilinuxoo7** [comment] 2022-07-12 03:31
I am using release v1.8.11 built from source after some changes.
Going through a previous issue #21397 , I found a tx that was causing it. But, there is no tx error in both validators. Both the leader node as well as the other validator processes the tx without any error. This tx changes some data of a program.
My findings are, 
The leader calculates accounts_delta_hash of that account different from the other validator(which is not leader). Though both are processing the tx without any error.
I see this difference in logs at that particular bank, the leader node has this accounts db update log, which the validator doesn't have.
`[2022-07-10T04:50:48.598919181Z INFO  solana_metrics::metrics] datapoint: accounts_db_store_timings hash_accounts=0i store_accounts=208i update_index=16i handle_reclaims=0i append_accounts=0i find_storage=0i num_accounts=35i total_data=509155i read_only_accounts_cache_entries=30i read_only_accounts_cache_data_size=182535i read_only_accounts_cache_hits=36i read_only_accounts_cache_misses=1i calc_stored_meta_us=12i
[2022-07-10T04:50:48.598936042Z INFO  solana_metrics::metrics] datapoint: accounts_db_store_timings2 recycle_store_count=0i current_recycle_store_count=13i current_recycle_store_bytes=2158592i create_store_count=0i store_get_slot_store=0i store_find_existing=0i dropped_stores=0i`

Is there any way to know which state is being hashed by both of the nodes, I mean which account's state, before the tx execution or after that.

**Comment by steviez** [comment] 2022-07-12 04:30
> Is there any way to know which state is being hashed by both of the nodes, I mean which account's state, before the tx execution or after that.

Yes, we do this when debugging issues ourselves. It is a fairly manual process, but the following document has some insights and tips on how to hone in on what might be causing the issue.
https://github.com/solana-labs/solana/wiki/Debugging-Consensus-Failures

> I am using release v1.8.11 built from source after some changes

Given that you're running such an old version (v1.8.11 was tagged on 12/14/2021 and mainnet is currently on v1.10), I don't think I can justify spending more time to help you with this over doing other stuff. My advice would be:
- Run with your changes reverted (ie run v1.8.11)
    -  This will verify if your changes are the cause of the consensus deviation
- Assuming v1.8.11 shows issue (vindicating your changes), rebase your changes on top of latest v1.10 tag
    - This will confirm if the issue has since been fixed

As for trying to call out a specific commit, there have been multiple consensus breaking issues that we've fixed since the release you're using. I can't see a scenario in which trying to identify and cherry-pick all of these would be a better route than upgrading.

I'm going to close this issue out given the dated version. If you are able to reproduce the issue on v1.10 (and confirm your changes aren't causing the deviation), I'd gladly re-open the issue and jump in to debug further. Otherwise, I imagine we fixed the issue as we attach high priority to these kinds of failures.

**Closed by steviez** 2022-07-12 04:30 UTC

**Comment by kalilinuxoo7** [comment] 2022-07-12 04:44
> Yes, we do this when debugging issues ourselves. It is a fairly manual process, but the following document has some insights and tips on how to hone in on what might be causing the issue.
https://github.com/solana-labs/solana/wiki/Debugging-Consensus-Failures

I have already followed this guide. Just please tell me how can I debug which state is being used to calculate accounts hash of a particular account.
If i want to print or log data of this account when hash is being taken of it. How can I do that? Please just help me in this. 
`[2022-07-11T09:05:26.899382576Z WARN  solana_runtime::accounts_hash] Updated Account: (3DhEbwSRa985orCXEsjMm3AApG7tQDHZdKk1vq3yfmRt, 5eEBQ33cgremdAwceQjNU5cMYVHes2FZbbSQidPZRk7y)`

And even without my changes it had same problem. I will try on 1.10.

**Comment by steviez** [comment] 2022-07-12 05:22
I would still recommend trying on `v1.10` first, but I updated the wiki with a patch print account state:
https://github.com/solana-labs/solana/wiki/Debugging-Consensus-Failures#log-differing-accounts-details
