### ISSUE TITLE
Add the ability to sign a message to the Solana Ledger app

### ISSUE THREAD

**Issue by fragosti** [solana-labs/solana#21366] opened 2021-11-19 17:18 UTC
#### Problem

At [Phantom](https://phantom.app/), we've implemented a `signMessage` [feature](https://docs.phantom.app/integrating/signing-a-message) that allows an application to request signing an arbitrary message. This feature is being used by Audius on Solana to authenticate users, and is popular on Ethereum for applications like OpenSea that also rely on it to authenticate their users.  

A long-standing issue with this feature is that the Solana Ledger app (https://github.com/LedgerHQ/app-solana) does not support signing arbitrary messages, and so this feature does not work for Ledger users. 

#### Proposed Solution

Add support for signing arbitrary data (or just utf8 strings) to the Solana Ledger app. @t-nelson mentioned that support would need to be added to `solana-remote-wallet` and the CLI as well.

**Comment by t-nelson** [comment] 2021-11-19 17:20
Would ASCII do? The Ledger's font doesn't support all of UTF8 and I'm fairly certain a UTF8 compliant transaction message could be constructed

**Comment by fragosti** [comment] 2021-11-19 17:24
If there are security reasons for just doing ASCII, sure, but our preference would be UTF8. 

https://docs.phantom.app/integrating/signing-a-message

**Comment by t-nelson** [comment] 2021-11-19 17:31
Yeah the inability of the ledger to actually display all UTF8 messages is pretty much a non-starter IMO

**Comment by kinosang** [comment] 2021-11-24 08:06
Is there any draft or standard about the signature? Does it use the similar algorithm as BIP-322 and ERC-191?

**Comment by dahifi** [comment] 2021-12-09 17:28
Star Atlas would like this fixed as well. The profile update page uses the message signing to allow clients to select avatar pics, and it works fine w Phantom and SolFlare, but Ledger users are not. I've been trying to trace the issue down and dealing with Ledger support the last few days. I've pinged their Discord admin and asked for a dev to pop in here for help figure out whether they can contribute utf support of if it'll have to be one of these 'allow blind signing' types of things.

**Comment by mralbertchen** [comment] 2021-12-14 03:51
Genopets would like this fixed as well - our summoning / hatching function requires a signature of the answers to the hatching questions. It works well on Phantom but Ledger users currently have to send the eggs over to a non-ledger address in order to hatch.

**Comment by dahifi** [comment] 2021-12-15 15:11
I spoke to @t-nelson via TG last week, he said that they actually don't need Ledger's assistance with this and that they (Solana) should be able to deliver a fix in 22Q1.

This works for Star Atlas team but obviously might need higher priority based on other projects' needs.

**Comment by adamq-q** [comment] 2021-12-27 04:10
Portals would like this fixed as well! 🌀

**Comment by bmeeder22** [comment] 2021-12-29 16:32
[Phantasia](https://phantasia.app) would like this feature as well

**Comment by Caribosaurus** [comment] 2021-12-31 20:02
Same thing for https://piratesdelsol.com

**Comment by emperorgurgeh** [comment] 2022-01-02 00:51
Planet owners at www.desolate.space are also begging for this :)

**Comment by kirksgithub** [comment] 2022-01-10 16:25
I will bump this also from Grape (https://verify.grapes.network with over 250k verified wallets) - we use message signing to verify user wallets, currently Ledger is supported only with a transaction from/to the same wallet, drawback is that the user will end up paying the gas fees until support for message signing is rolled out with Ledger

**Comment by GoJiTa972** [comment] 2022-01-22 04:34
And I bump because I can't sign in into https://game.playmysteria.com/ nor grape as above.

**Comment by xavierleung** [comment] 2022-01-23 10:41
We at https://solparasites.com/ also make use of message signing for our verification system and have many users with Ledger wallets waiting for message signing support with Ledger.

**Comment by grimAgent** [comment] 2022-01-26 03:11
Adding a vote to this feature from https://grimsyndicate.com

**Comment by candymachinist** [comment] 2022-01-28 21:31
Monsterz DAO at https://monsterzdao.com would like to vote for this fix as well

**Comment by sThReal** [comment] 2022-01-29 02:14
CyberConnect at https://sol.cyberconnect.me also like want this to be fixed as well

**Comment by raphaelpc** [comment] 2022-02-01 19:26
Our team at The Frameboy Journey (https://www.theframeboy.com/) would also like to vote for this to be fixed as well

**Comment by quarantaquatro** [comment] 2022-02-08 12:50
Metavillage at https://metavillage.app/ also want this to be fixed as well

**Comment by t-nelson** [comment] 2022-02-08 17:14
> ... would like to vote for this fix as well

This is Github, not a DAO.  It's clear that this is desired, finding time to do the work is the remaining factor

**Comment by 0xWernher** [comment] 2022-02-13 03:26
Engineer behind [Metavillage](https://metavillage.app) here. We'd also really appreciate this fix, as hundreds of our members use Ledger for security reasons.

Our use case: we ask users to sign a message to authenticate with our web app. ASCII support should be enough but UTF8 is preferable.

**Comment by rez-cpu** [comment] 2022-02-17 22:31
any update on this?

**Comment by dahifi** [comment] 2022-02-18 02:59
> > ... would like to vote for this fix as well
> 
> This is Github, not a DAO. It's clear that this is desired, finding time to do the work is the remaining factor

Trevor, 

I see the Ledger program is written in C. Is the availability of C developers an issue here? I think at this point that we might be able to put a gitcoin bounty on this and move things forward. 

What will it take to make this happen before April 1?

**Comment by RustySol** [comment] 2022-02-24 03:07
Solanalanders at liqnft.com/solanaland would also love the fix!!

**Comment by nonfungible-dev** [comment] 2022-02-27 02:48
Pesky Penguins would love a fix for this as well 😁

**Comment by zkRemda** [comment] 2022-02-28 17:30
Same for me

**Comment by zkRemda** [comment] 2022-02-28 19:06
> tfw the issue is brigaded by people who don't know the difference between a fix and a feature request

To be fair, it is a fix for a broken functionality. You could argue it is a feature request although the user experience needs to be considered.

**Comment by t-nelson** [comment] 2022-02-28 19:07
What never existed cannot be broken

**Comment by zkRemda** [comment] 2022-02-28 19:12
> What never existed cannot be broken

It does exist, just not for ledger 😊

**Comment by quarantaquatro** [comment] 2022-02-28 19:18
You can call it certainly as you want, it's a problem that needs to be addressed urgently if Solana doesn't want to fall behind! 

Every day when another user lost his assets, more Ledgers will be out there and this is a serious problem for every Solana project. Many things are on hold because of that.

**Comment by zkRemda** [comment] 2022-02-28 19:23
> You can call it certainly as you want, it's a problem that needs to be addressed urgently if Solana doesn't want to fall behind! 
> 
> 
> 
> Every day when another user lost his assets, more Ledgers will be out there and this is a serious problem for every Solana project. Many things are on hold because of that.

I don't see it that urgent, I know it is important but not crucial. Sign arbitrary messages current usage is mainly for NFTs and web3 apps. There are much more priorities on Solana development. 

What we could do is collect a bounty between all the projects interested in this feature and leave the Solana developers handling core issues.

**Comment by mvines** [comment] 2022-02-28 19:51
> What we could do is collect a bounty between all the projects interested in this feature and leave the Solana developers handling core issues.

Yep, there seems to be enough brigaded here that there ought to be somebody from the community that is willing to do more than just direct other users to comment on this issue.  Brigading will not be rewarded around here

**Comment by t-nelson** [comment] 2022-02-28 20:00
FWIW I'm not generally interested in a community contribution to the Ledger App for this issue.  There's some refactoring that should take place first and it will take longer to communicate the requirements to an unfamiliar contributor than to implement it myself.

I intend to prioritize this work before the end of Q1

**Comment by grimAgent** [comment] 2022-02-28 20:37
> > What we could do is collect a bounty between all the projects interested in this feature and leave the Solana developers handling core issues.
> 
> Yep, there seems to be enough brigaded here that there ought to be somebody from the community that is willing to do more than just direct other users to comment on this issue. Brigading will not be rewarded around here

How are the replies here considered brigading? Comments are not THAT often and AFAIK they are all coming from project devs who are looking forward to use this in their apps. I don't see anyone directing their users to comment here.

Also, although I'm sure there must be other priorities for Solana core, NFTs and web3 apps are giving HUGE exposure to the whole Solana environment, so I don't see why there is a need to undermine them?

Thank you @t-nelson for trying to prioritize this

**Comment by quarantaquatro** [comment] 2022-03-01 04:50
Thank you for your reply. I already thought they blind took over.

**Comment by kryptoj** [comment] 2022-03-01 11:44
Thank @t-nelson. 
The MLK Fam @ [milktoast.world](https://www.milktoast.world) is looking forward to this issue being fixed! 🙏

**Comment by karnaker** [comment] 2022-03-05 02:15
I would also like to see this fixed. I'm a user; I purchased a Ledger Nano S directly from Ledger, and my primary use case for Ledger is the Solana app. The ability to securely sign a message via the Solana Ledger app has value. FWIW, nobody brigaded me -- I was simply Google searching for a solution to this problem, and thought to add a user's perspective.

**Comment by vjohnston** [comment] 2022-03-09 20:38
+1, thank you for trying to prioritize this, @t-nelson! [Little Atlas](https://app.littleatlas.xyz/) is also really looking forward to a fix 🙏🙏

**Comment by cryptowazza** [comment] 2022-03-12 15:23
Hopefully this will be added soon. SolanaFloor and many other platform users have been requesting this for months.

**Comment by Gousi1991** [comment] 2022-04-06 08:54
Hello, it is really needed for www.monkeyleague.io right now. There is a sign-in necessary to claim gifts and many users dont feel safe without ledger in this space. Please find a workaround for this. would be much appreciated.

**Comment by 0xfunfacts** [comment] 2022-04-06 09:45
Same for me. i do not want to put my stuff into an unsave browserwallet. so please add this as soon as possible!

**Comment by quarantaquatro** [comment] 2022-04-06 14:01
Hi everybody, I know it won't solve it for everyone but as a simple workaround, I basically let the user authorize a mini transaction from his wallet to his wallet! This costs him some micro cents but works fine in my project. Of course, it's not a solution for people who have to sign in nonstop but it works well for some situations where you just want to verify something or authorize something special for this moment. At least in my case, no users have any issue with this workaround.

Having said that, YES this feature is really needed and at least some type of news/update would help to either build on better workarounds or wait until we get this feature. Thank you everyone!

**Comment by AndyQDesign** [comment] 2022-04-06 16:46
Please add this functionality , games need it .

**Comment by akalasol** [comment] 2022-04-06 17:55
monkeyleague.io is in urgent need of this feature, please add it! appreciate your work.

**Comment by quarantaquatro** [comment] 2022-04-06 22:24
> highly recommend _against_ training users to sign transactions for this use-case. you're grooming them to be socially engineered

As I said, it's a temp solution for those of us who can't wait any longer! Plus, it is a matter of **making clear to the user what is happening**. They are free to use or not to use it. However, if you have a project with hundreds or thousands of users who cant participate otherwise, I still prefer to give them a choice.

**Comment by pdesgrip** [comment] 2022-04-08 10:55
Would also like to see this fixed as I can't use Ledger with Monkeyleague.io

**Comment by karnaker** [comment] 2022-04-09 20:23
> highly recommend _against_ training users to sign transactions for this use-case. you're grooming them to be socially engineered

I agree with this. For better or worse, the crypto landscape is full of scams, frauds, and bad actors. I really love products that can deliver a good experience in this context -- isn't that why we're using Ledger in the first place? Hopefully folks with @t-nelson's mindset will make crypto safer for people who are trying to do good work or perform legitimate transactions.

**Comment by rivendale** [comment] 2022-04-11 16:03
would love to have a fix for sites like: https://app.monkeyleague.io/store

**Comment by zkRemda** [comment] 2022-04-11 16:14
For all the people requesting this for monkeyleague, ask your developers to seek for an alternative to this, take a look at implementations from other projects like pesky penguins, yawww, matrica, grape, etc.

To sign arbitrary data with a ledger is not a priority for Solana core rn.

**Comment by ianlandsman** [comment] 2022-04-11 17:02
It's absolutely nuts that this wouldn't be a priority.

**Comment by quarantaquatro** [comment] 2022-04-11 17:40
> o sign arbitrary data with a ledger is not a priority for Solana co

Ridiculous! Not much more I can say about this comment.

**Comment by t-nelson** [comment] 2022-04-12 01:20
> For all the people requesting this for monkeyleague, ask your developers to seek for an alternative to this, take a look at implementations from other projects like pesky penguins, yawww, matrica, grape, etc.
> 
> To sign arbitrary data with a ledger is not a priority for Solana core rn.

every post in this vein demotes it in my priority queue! keep it up!  you brought two tag-alongs with you gg.

yes, of course off chain message signing is prioritized below relieving congestion.  get over yourselves

**Comment by Anas11180** [comment] 2022-04-12 12:16
would love to have a fix for sites like: https://app.monkeyleague.io/store ❤️

**Comment by zkRemda** [comment] 2022-04-12 12:50
> > For all the people requesting this for monkeyleague, ask your developers to seek for an alternative to this, take a look at implementations from other projects like pesky penguins, yawww, matrica, grape, etc.
> 
> > 
> 
> > To sign arbitrary data with a ledger is not a priority for Solana core rn.
> 
> 
> 
> every post in this vein demotes it in my priority queue! keep it up!  you brought two tag-alongs with you gg.
> 
> 
> 
> yes, of course off chain message signing is prioritized below relieving congestion.  get over yourselves

Seems like you miss understood my message, nvm

**Comment by safaiyeh** [comment] 2022-04-17 19:48
This is some we need at Magic Eden as well. Our profile login is dependent on a message signing

**Comment by 0xMQQ** [comment] 2022-04-26 04:28
> > o sign arbitrary data with a ledger is not a priority for Solana co
> 
> Ridiculous! Not much more I can say about this comment.

Totally agree. So many major web3 apps in Solana, including some of the biggest NFT marketplaces, depend on this functionality right now. It sounds so arrogant to say that improving user security and experience is not a priority.

**Comment by tribixbite** [comment] 2022-04-26 14:06
We need this for [https://claim-map.metaversol.com](https://claim-map.metaversol.com). As long as we are all sharing lol.

**Comment by Anas11180** [comment] 2022-04-29 02:17
would love to have a fix for sites like: https://app.monkeyleague.io/store

**Comment by NickTikhonov** [comment] 2022-05-02 23:47
**This fix is crucial - it blocks adoption of good security practices for Solana end-users.** cc @vjohnston 

**Relevant product context:** Signing arbitrary data using a wallet is necessary for creating progressively decentralised applications. These are applications that experiment with features in web2, before implementing them on-chain. They rely on a mixture of both web3 and web2 (API backend) interactions. Many of the companies that are building products this way have stated that this is a blocker for them ^

**Concrete use case for this feature:** One common use case is creating a separate user account, stored in a database tied to a specific wallet owner. This pattern is incredibly common - as it allows the storage of data off-chain, using centralised services - but still have that data be secured by the private key of a wallet holder. For example, this can be used to store rich information for user profiles - which would otherwise be very expensive to store on-chain!

**Specific technical issue that blocks the use case:** This example requires the user to sign a message and send that to an API backend - which verifies that the sender is indeed the holder of the private key (and hence wallet). Similarly any write operation to an API, that is tied to a user account, requires further signatures - if the application chooses not to implement a bespoke authentication flow (many choose not to).  

**Impact on Solana end-users:** Currently, keeping this feature as low-priority prevents many high-quality web3 user experiences from being available to Ledger users. For example, in our application (https://app.littleatlas.xyz) - you can't use any features aside from minting (for example, creating custom profiles and visual status updates) if you are a Ledger user. 

Using a software wallet like Phantom and compromising security is the only way for our users to have the optimal user experience when using web3 applications on Solana. 

Hence, unless there is a good workaround for Ledger users that we aren't aware of, we'd argue that reprioritising this should be considered!

**Comment by kizzx2** [comment] 2022-05-14 09:47
Since it isn't like this is coming any time soon, I've created an app that let's user just send a amount of SOL to "sign a message": https://github.com/kizzx2/solana-sign-with-payment

**Comment by queiroz** [comment] 2022-05-17 14:40
Me as a Ledger loyal customer and collecting NFT's and going over many Dapps, they all seem to rely o message signing and yet I am forced to move assets off Ledger. This should be prioritised as many Ledger users in the Solana eco-system are moving away because they have no other alternative.

**Comment by fakenine** [comment] 2022-05-30 10:29
Hello, any updates on this?

I'm building an app and need the sign in feature for security reasons.
Workaround would be to do like Grape and send a transaction as verification, but this really isn't practical.

Signing messages would be a huge step forward for Ledger.

**Comment by alexgidge** [comment] 2022-06-27 15:28
Bumping again - Required support for authentication using Ledger. This is something every Web3 App should need for authentication

**Comment by CryptoGod69420** [comment] 2022-07-01 15:30
Magic Eden wallet drained last week. Can you guess why? 

Oh ya it's because in order to get the magic ticket airdrop you were literally forced off your ledger. 

End users keep this space alive at the EOD, whatever we deem necessary should rest at top of dev to-do list

Been in Sol long time, I've personally waited over a year and a half for this capability, how much longer must we wait, and how much more must we lose along the way

**Comment by quarantaquatro** [comment] 2022-07-01 17:06
> Magic Eden wallet drained last week. Can you guess why?
> 
> Oh ya it's because in order to get the magic ticket airdrop you were literally forced off your ledger.
> 
> End users keep this space alive at the EOD, whatever we deem necessary should rest at top of dev to-do list
> 
> Been in Sol long time, I've personally waited over a year and a half for this capability, how much longer must we wait, and how much more must we lose along the way

Don't expect any reply from them here, they do not care much about this subject, unfortunately!

**Comment by levicook** [comment] 2022-07-05 15:37
Uh, wow. Showed up to this thread ready to contribute now feel like that would be unwelcome and a waste of time.  gl everyone.

**Comment by ChewingGlass** [comment] 2022-07-07 21:11
Not that it's particularly helpful, but both [Strata Protocol](https://strataprotocol.com/) and [Lit Protocol](https://litprotocol.com/) need this. What is the holdup? Any way I can help?

**Comment by solserer-labs** [comment] 2022-07-08 08:44
How is signing messages with a hardware wallet NOT a priority? Tbh thought we had this forever.

**Comment by 21e8** [comment] 2022-07-15 06:34
ok now lets assemble a list of people who are qualified to do this, we all agree its needed.

**Comment by jon64digital** [comment] 2022-07-22 15:05
> every post in this vein demotes it in my priority queue! 

I had no idea the Solana devs were 8 years old.

Seriously, this is BASIC functionality and necessary for lots of sites to function properly. The fact that this ticket is still open is embarrassing and saying it's a feature not a bug?

"Hey, my car doesn't have an engine, but that's a feature not a bug, I like it that way. Oh, and BTW it never had one so it can't be broken!"

**Comment by zkRemda** [comment] 2022-07-22 15:56
> 
> 
> > every post in this vein demotes it in my priority queue! 
> 
> 
> 
> I had no idea the Solana devs were 8 years old.
> 
> 
> 
> Seriously, this is BASIC functionality and necessary for lots of sites to function properly. The fact that this ticket is still open is embarrassing and saying it's a feature not a bug?
> 
> 
> 
> "Hey, my car doesn't have an engine, but that's a feature not a bug, I like it that way. Oh, and BTW it never had one so it can't be broken!"
> 
> 
> 
> 
> 
> 

Hi, just to add some context. To sign arbitrary messages is not a solana feature. If you read the first message in this thread, is explained it is a feature implemented by Phantom but is not a core functionality in Solana. 

Remember the priority for Solana devs is Solana core, not a side functionality implemented by a third party. 

The whole point of a blockchain is to have **On-chain** transactions, to login with an arbitrary message is a web2 experience. So go back to your communities and design a web3 solution for it rather than complaining about solana not prioritizing things that aren't important for the architecture.

**Comment by grimAgent** [comment] 2022-07-22 16:05
> > > every post in this vein demotes it in my priority queue!
> > 
> > 
> > I had no idea the Solana devs were 8 years old.
> > Seriously, this is BASIC functionality and necessary for lots of sites to function properly. The fact that this ticket is still open is embarrassing and saying it's a feature not a bug?
> > "Hey, my car doesn't have an engine, but that's a feature not a bug, I like it that way. Oh, and BTW it never had one so it can't be broken!"
> 
> Hi, just to add some context. To sign arbitrary messages is not a solana feature. If you read the first message in this thread, is explained it is a feature implemented by Phantom but is not a core functionality in Solana.
> 
> Remember the priority for Solana devs is Solana core, not a side functionality implemented by a third party.
> 
> The whole point of a blockchain is to have **On-chain** transactions, to login with an arbitrary message is a web2 experience. So go back to your communities and design a web3 solution for it rather than complaining about solana not prioritizing things that aren't important for the architecture.

So if it's not important for Solana, why is Anatoly supporting that this is implemented? 
https://twitter.com/aeyakovenko/status/1547634308646481923

I don't understand the push back on this issue (whether it is an issue or a feature request). It is clear it is wanted by a LOT of communities. Implementing this is a net positive for Solana as a whole.

**Comment by zkRemda** [comment] 2022-07-22 16:42
> So if it's not important for Solana, why is Anatoly supporting that this is implemented?
> https://twitter.com/aeyakovenko/status/1547634308646481923

It would happen... eventually. Just chill and wait. 😉

**Comment by grimAgent** [comment] 2022-07-22 16:46
> > So if it's not important for Solana, why is Anatoly supporting that this is implemented?
> > https://twitter.com/aeyakovenko/status/1547634308646481923
> 
> It would happen... eventually. Just chill and wait. 😉

Oh I'm chilling and waiting since January. No complaints from me on how long it takes to implement this. I'm just commenting on the pushback itself...

**Comment by 0xMQQ** [comment] 2022-07-25 06:42
> > > every post in this vein demotes it in my priority queue!
> > 
> > 
> > I had no idea the Solana devs were 8 years old.
> > Seriously, this is BASIC functionality and necessary for lots of sites to function properly. The fact that this ticket is still open is embarrassing and saying it's a feature not a bug?
> > "Hey, my car doesn't have an engine, but that's a feature not a bug, I like it that way. Oh, and BTW it never had one so it can't be broken!"
> 
> Hi, just to add some context. To sign arbitrary messages is not a solana feature. If you read the first message in this thread, is explained it is a feature implemented by Phantom but is not a core functionality in Solana.
> 
> Remember the priority for Solana devs is Solana core, not a side functionality implemented by a third party.
> 
> The whole point of a blockchain is to have **On-chain** transactions, to login with an arbitrary message is a web2 experience. So go back to your communities and design a web3 solution for it rather than complaining about solana not prioritizing things that aren't important for the architecture.

I am sorry to say that, but this is exactly what I meant "**arrogant**". You make it sound like everyone in this thread is just dumbass who doesn't understand web3 and blockchain. I don't know how this is helpful. 

I would suggest you read the first message again. Phantom, the most widely used Solana wallet, one of the most important piece in the Solana ecosystem, came to the core team for help! and you tell them to "go back"?? 

I have searched around about this issue since months ago, and I am fully aware that there are similar open issues in Ledger and Phantom's github repos. This is not a super technical challenging issue, but it has big impact and it does require some coordination between multiple parties. This is why people have come here for help. This is where people expect the core team can take some leadership to bring partners together to resolve it. 

Yes, this may not be a direct tech responsibility of the core team. But instead of tell people to "go back to your communities", how about help pass the message up, raise awareness, and find the right contact person that can help coordinate and resolve the issue? Thank you.

**Comment by josezy** [comment] 2022-07-25 16:21
I ended up creating a transaction with a memo instruction in it (a nonce) then verifying the signature (and the nonce), not ideal but it worked (tx is never sent to the chain, only signed and verified)

```typescript
import { PublicKey, Transaction, TransactionInstruction } from "@solana/web3.js"

const MEMO_PROGRAM_ID = new PublicKey(
  "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
)

export const buildAuthTx = (nonce: string): Transaction => {
  const tx = new Transaction()
  tx.add(
    new TransactionInstruction({
      programId: MEMO_PROGRAM_ID,
      keys: [],
      data: Buffer.from(nonce, "utf8"),
    })
  )
  return tx
}

export const validateAuthTx = (tx: Transaction, nonce: string): boolean => {
  try {
    const inx = tx.instructions[0]
    if (!inx.programId.equals(MEMO_PROGRAM_ID)) return false
    if (inx.data.toString() != nonce) return false
    if (!tx.verifySignatures()) return false
  } catch (e) {
    return false
  }
  return true
}

```

How to use it:
```typescript
// Create tx
const tx = buildAuthTx("test-nonce")
tx.feePayer = wallet.publicKey // not sure if needed but set this properly
tx.recentBlockhash = (await connection.getLatestBlockhash()).blockhash // same as line above

// Encode and send tx to signer, decode and sign
signedTx = await wallet.signTransaction(tx)

// Encode, send back, decode and verify tx signature
const validSignature = validateAuthTx(tx, "test-nonce")
```

**Comment by jon64digital** [comment] 2022-07-26 13:52
> The whole point of a blockchain is to have **On-chain** transactions, to login with an arbitrary message is a web2 experience. So go back to your communities and design a web3 solution for it rather than complaining about solana not prioritizing things that aren't important for the architecture.

Wow. 

Just.... wow ......

**Comment by jordansexton** [comment] 2022-07-27 23:52
> I ended up creating a transaction with a memo instruction in it (a nonce) then verifying the signature (and the nonce), not ideal but it worked (tx is never sent to the chain, only signed and verified)

This is a cool solution!

A way you could make it safe for the user to sign without any risk of costing them SOL is to have the memo instruction require a signature from an account public key that you can't have the private key for (like `new PublicKey(0)`).

This should make it so that the instruction would fail in signature verification if ever submitted, and could never cost them fees. Alternatively, you could just set the fee payer to this (which of course, can't pay fees at all).

**Comment by aeyakovenko** [comment] 2022-11-02 16:59
Fixed in https://github.com/solana-labs/solana/pull/27456

**Comment by grimAgent** [comment] 2022-11-02 19:14
> Fixed in #27456

It's a Breakpoint miracle! 🙌

Jokes aside, thank you so very much to everyone who worked on this.  ❤️

**Comment by dahifi** [comment] 2022-11-02 20:12
> 

ZOMG thank you so much.

**Comment by 0xMQQ** [comment] 2022-11-03 09:34
> Fixed in #27456

This is AWESOME! Thank you so much for working on this!

**Comment by vbstreetz** [comment] 2022-11-07 17:10
@jordansexton looking forward to seeing this working in the adapter lib..

**Comment by roguzh** [comment] 2022-11-18 17:08
> could just set the fee payer to this (which of course, can't p

I have been following your suggestions but got confused at the part about requiring signature from an account public key that you can't have the private key. 

Would it be possible to verify the actual wallet's (user's) signature?

**Closed** 2022-11-18 17:50 UTC

**Comment by JonCognioDigital** [comment] 2022-11-22 21:14
For those of us running a site which uses the Solana Wallet Adapter library supporting Phantom and Solflare, do we need to do anything to implement this? DO we have to wait for Phantom/Solflare/Ledger to add something or do we need to do anything ourselves?

**Comment by jordansexton** [comment] 2022-11-22 22:01
@JonCognioDigital yes, this is primarily on Phantom, Solflare, and other wallets to add support for.

It's also important to note that messages signed this way have a specific format, described here: https://github.com/solana-labs/solana/blob/e80f67dd58b7fa3901168055211f346164efa43a/docs/src/proposals/off-chain-message-signing.md

Wallets and apps will both need to update how they handle message signing in accordance with this.

**Comment by fragosti** [comment] 2022-11-22 22:07
We will be adding support for this at Phantom :)

**Comment by fakenine** [comment] 2023-05-29 21:57
Hello! Just installed version 1.4.1 and I've got the same error message cc @fragosti
