### ISSUE TITLE
Only one QUIC connection request can be handled at a time

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#26020] opened 2022-06-17 12:14 UTC
#### Problem
Only one connection can be handled at a time in the current QUIC server implementation. This means that a slow connection handshake could block other clients from connecting. The specific issue is that there is one task spawned for `run_server` which then runs a while loop that will only handle one new connection per loop.
https://github.com/solana-labs/solana/blob/752c851070873a180d815f8b4e447e8b83be2a38/streamer/src/nonblocking/quic.rs#L73

#### Proposed Solution
Handle connection handshakes in parallel

**Comment by pgarg66** [comment] 2022-06-17 13:13
I think we can handle 4, as the runtime has 4 threads.
```
const NUM_QUIC_STREAMER_WORKER_THREADS: usize = 4;
```

**Comment by jstarry** [comment] 2022-06-17 13:39
Yes, the runtime has 4 threads but only 1 thread is spawned for the incoming connection handler. That single thread uses a while loop to serially handle connection requests.

**Comment by pgarg66** [comment] 2022-06-17 13:44
I distinctly remember testing this condition a few months ago (that resulted in changing the worker thread limits). Maybe the code got changed since then. If so, it's worth testing (and fixing if needed).

**Comment by jstarry** [comment] 2022-06-17 13:52
Could you point me to where you added that test?

**Comment by pgarg66** [comment] 2022-06-17 14:48
The test was a bit invasive of the code, so it was not merged. I had pushed a branch here for reference: https://github.com/pgarg66/solana/commit/4c0cee038e7273c2184e32086312ae5c54894903

If you think the test replicates the issue here, we can try to instrument a test that can be merged, for future proofing.

**Comment by pgarg66** [comment] 2022-06-17 14:49
There were some discussions on Discord as well. Here's the link to the chat https://discord.com/channels/428295358100013066/935200678215835658/966406072803922032

Some excerpts from the chat, in case the link above doesn't work.

<img width="1342" alt="image" src="https://user-images.githubusercontent.com/40076733/174322139-0ce51cdf-4f85-4a52-8ccc-9031008def93.png">

**Comment by jstarry** [comment] 2022-06-17 14:51
Your test isn't related to this issue because it's testing delays _after_ the connection handshake is completed. I'm concerned with the client handshake itself.

**Comment by pgarg66** [comment] 2022-06-17 15:06
It would be nice if we could re/produce the issue. The handshake is handled completely inside `quinn` library. So if they don't have a knob/setting to introduce delays in the handshake, it'll be really tough to simulate this condition reliably in a test.

**Comment by jstarry** [comment] 2022-06-17 15:09
Do we agree that if it's possible to have a handshake that takes longer than a few milliseconds, then the current server implementation should be updated to ensure that handshakes are not processed serially? If so, then I think that someone should take on this issue and include a test that simulates a slow handshake along with the PR that fixes the issue.

**Comment by pgarg66** [comment] 2022-06-17 22:51
Ok, confirmed that the connections handshake is sequential. So, if the handshake is slow (or the client is malicious and doesn't finish the handshake), the next connection setup request will take longer to process. I followed the same technique to induce the errors as here: https://github.com/solana-labs/solana/issues/26019#issuecomment-1159287741

**Closed** 2022-06-21 23:22 UTC
