### ISSUE TITLE
v0.23.5 mistakenly detects AVX and crashes on a perf-libs assertion

### ISSUE THREAD

**Issue by vkomenda** [solana-labs/solana#8304] opened 2020-02-15 14:16 UTC
#### Problem
I compiled v0.23.5 on a machine without AVX instructions. ~~Unlike earlier versions,~~ I checked and it turns out that earlier versions and this one detect AVX. In addition v0.23.5 appears to be more likely to crash on a Cuda assertion in perf-libs.
```
[2020-02-15T14:08:37.625484322Z INFO  solana_core::validator] AVX detected
...
[2020-02-15T14:12:53.778184785Z INFO  solana_validator] Validator initialized
ERR: invalid configuration argument cuda-ecc-ed25519/verify.cu 197
solana-validator: common/gpu_common.h:22: void cuda_assert(cudaError_t, const char*, int): Assertion `0' failed.
```
The crash happens ~~every~~ 3 out of 4 times, including when the validator ledger directory has been deleted. There seems to be no difference in the environment when the validator does start.

#### Proposed Solution

For a quick workaround, go back to v0.23.4, or perhaps experiment locally compiling Solana perf-libs (not attempted).

**Comment by mvines** [comment] 2020-02-15 17:07
What version of CUDA are you using?
Are you running into the AVX issue on a cloud machine, if so what kind so we can try to reproduce?

**Comment by vkomenda** [comment] 2020-02-15 17:22
I'm using CUDA version 10.2 from perf-libs. The machine is real, not virtual. Processor Xeon E5-1650. It supports AVX but not AVX2. I compile the node locally. GPU Nvidia GTX 1660 Ti.

**Comment by mvines** [comment] 2020-02-15 17:29
Thanks.  The "AVX detected" check is in fact only for AVX and not AVX2, so that part seems normal.

I'd love to hear if compiling perf-libs locally helps at all.  The machines we produce the release binaries on all do have AVX2 (but not AVX512)

**Comment by mvines** [comment] 2020-02-16 16:28
This crash was reported again today from a different user on 0.23.5

**Comment by mvines** [comment] 2020-03-16 15:08
This no longer seems to be an issue, I'm not hearing any Discord feedback about it reoccuring so closing for now

**Closed by mvines** 2020-03-16 15:08 UTC
