### ISSUE TITLE
Issues with solana test validator

### ISSUE THREAD

**Issue by NAJIB-B** [solana-labs/solana#28740] opened 2022-11-03 18:00 UTC
#### Problem

I am new to solana, when I ran solana-test-validator on my wls ubuntu  it's was saying Aborted (core dumped)
So download the source code from 
`git clone https://github.com/solana-labs/solana.git`
I built it using this commad
`cargo build --bin solana-test-validator --release`
and I ran it using 
`./target/release/solana-test-validator`
But I am still getting this error

Ledger location: test-ledger
Log: test-ledger/validator.log
⠁ Initializing...
Illegal instruction (core dumped)

**Comment by NAJIB-B** [comment] 2022-11-03 18:06
this is the log
`
[2022-11-03T18:05:04.738486300Z INFO  solana_test_validator] solana-validator 1.15.0 (src:devbuild; feat:2215009844)
[2022-11-03T18:05:04.742613000Z INFO  solana_test_validator] Starting validator with: ArgsOs {
        inner: [
            "./target/release/solana-test-validator",
            "--log",
        ],
    }
[2022-11-03T18:05:04.754092800Z WARN  solana_perf] CUDA is disabled
[2022-11-03T18:05:04.756133300Z INFO  solana_perf] AVX detected
[2022-11-03T18:05:04.847840300Z INFO  solana_faucet::faucet] Faucet started. Listening on: 0.0.0.0:9900
[2022-11-03T18:05:04.876856800Z INFO  solana_faucet::faucet] Faucet account address: 1ZYwftVGC9SSZLuZFsHtZdkRdKPFv5PW5oLatEytsJ2
[2022-11-03T18:05:05.055931700Z ERROR solana_ledger::blockstore] Unable to increase the maximum open file descriptor limit to 1000000 from 1024  
[2022-11-03T18:05:05.058567200Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 1024
[2022-11-03T18:05:05.067090300Z INFO  solana_ledger::blockstore] Opening database at "test-ledger/rocksdb"
[2022-11-03T18:05:08.250285200Z INFO  solana_ledger::blockstore] "test-ledger/rocksdb" open took 3.2s
Illegal instruction (core dumped)
`

**Comment by steviez** [comment] 2022-11-07 04:27
I see that your machine lacks `AVX2` so this is seemingly a duplicate of https://github.com/solana-labs/solana/issues/28366; someone seemingly found a workaround here https://github.com/solana-labs/solana/issues/28366#issuecomment-1302667020.

Going to close this issue as I'm pretty confident about this being the same issue, but feel free to reopen if that ends up not being the case

**Closed by steviez** 2022-11-07 04:27 UTC
Labels: community

**Comment by Asta1984** [comment] 2024-12-25 06:33
Did it got resolved?

**Comment by NAJIB-B** [comment] 2024-12-25 08:18
I found another way out

**Comment by Asta1984** [comment] 2024-12-25 08:40
I am getting the same error, while i am trying to start `solana-test-validator` locally on a WSL Ubuntu can you guide up! how can i resolve this ?

**Comment by NAJIB-B** [comment] 2024-12-25 09:13
I am really sorry
It's been a while since I encountered the issue, so I can't remember how I
fixed it
Please forgive my incompetence

**Comment by Asta1984** [comment] 2024-12-25 09:32
Okay

**Comment by univerbil** [comment] 2025-01-05 00:15
SOLUTION

https://github.com/solana-labs/solana/issues/28366#issuecomment-1302667020

**Comment by univerbil** [comment] 2025-01-05 00:54
./target/release/solana-test-validator
Ledger location: test-ledger
Log: test-ledger/validator.log
⠐ Initializing...                                                               Illegal instruction (core dumped)
