### ISSUE TITLE
signature not found error on successful transactions

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9305] opened 2020-04-05 03:28 UTC
#### Problem

On the TdS testnet running v1.1.1, about 5 to 10% of transactions will fail quickly with "Custom: signature not found". Because it returned so quickly (not after a long timeout), checking the account balance will show that the balance has not changed, suggesting the transaction had been dropped. But the transaction didn't fail, and if you check that balance again 30 seconds later, you see it went through.

#### Proposed Solution

Debug and fix

cc: @mvines

**Comment by CriesofCarrots** [comment] 2020-04-05 03:53
This looks like it might be an rpc_client issue. That error is produced by `RpcClient::get_num_blocks_since_signature_confirmation`.

`RpcClient::send_and_confirm_transaction_with_spinner` first submits `get_signature_status_with_commitment` on the recent bank, and if that passes, uses `get_num_blocks_since_signature_confirmation` to count confirmations until the tx is confirmed on the root bank. These two client methods use the same Rpc method, `getSignatureStatuses`, so they should be returning the same transaction-status information.
The only difference between the rpc requests I can see is the number of rpc_client_request retries: `get_signature_status_with_commitment` sends up to 5 retries; `get_num_blocks_since_signature_confirmation` only sends 1. It may be that `get_num_blocks_since_signature_confirmation` query fails on occasion, but would succeed if retried.

Inspecting the api node for this log (https://github.com/solana-labs/solana/blob/49e2cc659320328aafe0a314462f7e15ef4827b4/client/src/rpc_client_request.rs#L67) may give us some more information about the query failure, and in the short term, bumping the retries may resolve the erroneous error.

**Comment by danpaul000** [comment] 2020-04-29 15:59
While doing some community distributions yesterday, we saw this error on the CLI `Error: Custom: signature not found` after a `transfer` command was given.  No txn signature was displayed, but the transaction did actually go through.

I tracked down a transfer where this error was shown and it looks like the same txn and signature 
is present in multiple slots in the ledger.  Is this a simple client re-try that perhaps the CLI is not handling correctly?

```
$ solana-ledger-tool -l ledger slot 8057838 | grep 5yX4A9aQm8N6rzJdQU2XAhNL4dYX1eVN4q4fXoL6qrfTZPDWRyNFLSZzPG4V5UjcmzLUwUnic1dJb6LxjvNwvXyY -B 3 -A 15
[2020-04-29T15:39:40.178089009Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 65000
[2020-04-29T15:39:40.178113674Z INFO  solana_ledger::blockstore] Opening database at "/mnt/extra-disk/workspace/ledger/rocksdb"
[2020-04-29T15:39:40.415102373Z INFO  solana_ledger::blockstore] "/mnt/extra-disk/workspace/ledger/rocksdb" open took 236ms
  Entry 272 - num_hashes: 12279, hashes: ENPEtPDpcYZcTG6N2qDGsU1TrPPzEkdTv1UjvTQQ6mTQ, transactions: 1
    Transaction 0
      Recent Blockhash: B1gRoXqdVnL1Kq1teRkmVGztWbUvg2gmo88f1DiatqZB
      Signature 0: 5yX4A9aQm8N6rzJdQU2XAhNL4dYX1eVN4q4fXoL6qrfTZPDWRyNFLSZzPG4V5UjcmzLUwUnic1dJb6LxjvNwvXyY
      Header: MessageHeader { num_required_signatures: 1, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 1 }
      Account 0: 5q54XjQ7vDx4y6KphPeE97LUNiYGtP55spjvXAWPGBuf
      Account 1: BhNqfnpaXywWmYcndg7BBgrTbs4Q5s9XD99Fc6yZYvdy
      Account 2: 11111111111111111111111111111111
      Instruction 0
        Program: 11111111111111111111111111111111 (2)
        Account 0: 5q54XjQ7vDx4y6KphPeE97LUNiYGtP55spjvXAWPGBuf (0)
        Account 1: BhNqfnpaXywWmYcndg7BBgrTbs4Q5s9XD99Fc6yZYvdy (1)
        Transfer { lamports: 31000000000 }
      Status: Ok
        Fee: 5000
        Account 0 balance: 1395.0002 SOL -> 1364.000195 SOL
        Account 1 balance: 31 SOL -> 62 SOL
        Account 2 balance: 0.000000001 SOL
  Entry 273 - num_hashes: 221, hashes: JCsif2TrcurrpUh5sqmM5MPTgivmLMt8u7LkNq3Dm2dM, transactions: 0
```

```
$ solana-ledger-tool -l ledger slot 8057841 | grep 5yX4A9aQm8N6rzJdQU2XAhNL4dYX1eVN4q4fXoL6qrfTZPDWRyNFLSZzPG4V5UjcmzLUwUnic1dJb6LxjvNwvXyY -B 3 -A 15
[2020-04-29T15:39:29.504717986Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 65000
[2020-04-29T15:39:29.504748508Z INFO  solana_ledger::blockstore] Opening database at "/mnt/extra-disk/workspace/ledger/rocksdb"
[2020-04-29T15:39:29.760710388Z INFO  solana_ledger::blockstore] "/mnt/extra-disk/workspace/ledger/rocksdb" open took 255ms
  Entry 263 - num_hashes: 11984, hashes: DdK6yQ1jajkP5PujEXEwaNEiNzGPzCM8or7W1m9tEYXk, transactions: 1
    Transaction 0
      Recent Blockhash: B1gRoXqdVnL1Kq1teRkmVGztWbUvg2gmo88f1DiatqZB
      Signature 0: 5yX4A9aQm8N6rzJdQU2XAhNL4dYX1eVN4q4fXoL6qrfTZPDWRyNFLSZzPG4V5UjcmzLUwUnic1dJb6LxjvNwvXyY
      Header: MessageHeader { num_required_signatures: 1, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 1 }
      Account 0: 5q54XjQ7vDx4y6KphPeE97LUNiYGtP55spjvXAWPGBuf
      Account 1: BhNqfnpaXywWmYcndg7BBgrTbs4Q5s9XD99Fc6yZYvdy
      Account 2: 11111111111111111111111111111111
      Instruction 0
        Program: 11111111111111111111111111111111 (2)
        Account 0: 5q54XjQ7vDx4y6KphPeE97LUNiYGtP55spjvXAWPGBuf (0)
        Account 1: BhNqfnpaXywWmYcndg7BBgrTbs4Q5s9XD99Fc6yZYvdy (1)
        Transfer { lamports: 31000000000 }
      Status: Ok
        Fee: 5000
        Account 0 balance: 1395.0002 SOL -> 1364.000195 SOL
        Account 1 balance: 31 SOL -> 62 SOL
        Account 2 balance: 0.000000001 SOL
  Entry 264 - num_hashes: 516, hashes: 65j6CKsJDuBLZPhCajbPr5iqmwoHWPRCgiih7dJoYQow, transactions: 0
```

It appears a community user also hit this same error last night when calling `delegate-stake`

**Comment by danpaul000** [comment] 2020-04-29 16:39
Possibly related to @t-nelson 's forking hypothesis...the following transaction shown in the ledger-tool does not appear in the explorer and the intended recipient also claims the transfer never went through to the destination address:

```
$ solana-ledger-tool -l ledger slot 8058673 | grep 5m3vLj2cADWpSBhSMWxxvKfmZpZ4ndLAbgPQx4iNzv7ZKa97PHfENHtzCaYKNSHwLYCXTWt4x4ZwzEd2hgsEkKNy -B 5 -A 15
[2020-04-29T15:56:12.712779130Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 65000
[2020-04-29T15:56:12.712802202Z INFO  solana_ledger::blockstore] Opening database at "/mnt/extra-disk/workspace/ledger/rocksdb"
[2020-04-29T15:56:12.958898380Z INFO  solana_ledger::blockstore] "/mnt/extra-disk/workspace/ledger/rocksdb" open took 246ms
  Entry 129 - num_hashes: 12500, hashes: BUUwpCkzGg8BETShT4fKtfBKGWTsJqCNRF4LNpJH5VQ7, transactions: 0
  Entry 130 - num_hashes: 12500, hashes: 9FLeFmuiZtHWDzLc3uSv2kxP5mfYdBXnptFC9jZQtiim, transactions: 0
  Entry 131 - num_hashes: 6331, hashes: LxPxHa3Hyf85AFvsKh5yqHyJV7w3Gum2C3shD9yyZWA, transactions: 1
    Transaction 0
      Recent Blockhash: GVBJ68DFpwPL8BRoD4vyCgjwKhq95Fcj3b6xSNs9uU1i
      Signature 0: 5m3vLj2cADWpSBhSMWxxvKfmZpZ4ndLAbgPQx4iNzv7ZKa97PHfENHtzCaYKNSHwLYCXTWt4x4ZwzEd2hgsEkKNy
      Header: MessageHeader { num_required_signatures: 1, num_readonly_signed_accounts: 0, num_readonly_unsigned_accounts: 1 }
      Account 0: 5q54XjQ7vDx4y6KphPeE97LUNiYGtP55spjvXAWPGBuf
      Account 1: 7DSNen2Y7ZmotX1rTZaGxmaS3zrs5nJZceEtwfLqzYbM
      Account 2: 11111111111111111111111111111111
      Instruction 0
        Program: 11111111111111111111111111111111 (2)
        Account 0: 5q54XjQ7vDx4y6KphPeE97LUNiYGtP55spjvXAWPGBuf (0)
        Account 1: 7DSNen2Y7ZmotX1rTZaGxmaS3zrs5nJZceEtwfLqzYbM (1)
        Transfer { lamports: 150000000000 }
      Status: Ok
        Fee: 5000
        Account 0 balance: 837.00011 SOL -> 687.000105 SOL
        Account 1 balance: 0 SOL -> 150 SOL
        Account 2 balance: 0.000000001 SOL
  Entry 132 - num_hashes: 6169, hashes: 5bbUM2QvLKDegkvvbjAZB8WWD39PEJK5SJPJ7i7WVLPD, transactions: 0
```

**Comment by CriesofCarrots** [comment] 2020-04-29 16:44
> As this appears to potentially be an UNsucessful transaction, might deserve its own issue?
Yes, if this is an issue, I think this is separate.
Did the CLI incorrectly say it was confirmed? Or do we just want different handling of transactions that land in minor forks?
Fyi, `8058673` is not a confirmed block on mainnet-beta @danpaul000

**Comment by danpaul000** [comment] 2020-04-29 17:53
> Fyi, `8058673` is not a confirmed block on mainnet-beta @danpaul000

@CriesofCarrots transctions for non-confirmed blocks appear just like confirmed blocks in the ledger-tool, or am I missing some context?  That's a pretty big distinction to make if we aren't showing it right now.

**Comment by CriesofCarrots** [comment] 2020-04-29 17:56
> @CriesofCarrots transctions for non-confirmed blocks appear just like confirmed blocks in the ledger-tool, or am I missing some context? That's a pretty big distinction to make if we aren't showing it right now.

This is how I got that information:
```
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getConfirmedBlocks","params":[8058670,8058680]}' api.mainnet-beta.solana.com

{"jsonrpc":"2.0","result":[8058670,8058671,8058672,8058675,8058676,8058678,8058679],"id":1}
```

I don't have any experience using the ledger-tool. I would like to learn, but I currently don't have any insight as to what it is/isn't or should/shouldn't be communicating about a block.

**Comment by mvines** [comment] 2020-04-29 17:58
ledger-tool just dumps what's in each slot, so it's behaving as I'd expect.   We've not yet added a way to view whether a given slot is in the root path or not

**Comment by danpaul000** [comment] 2020-04-29 19:03
Okay, so my comment about the unsuccessful txn is really more of a missing feature on the ledger-tool than a bug on the RPC client, that's good.

**Comment by ericlwilliams** [comment] 2020-04-29 19:23
Two more transactions, with this error, that **didn't** go through:

http://explorer.solana.com/transactions/5beS2EMnHurQXmQzkTZiLqx2bKWkp9CYeCPKJ5CRCnismqG6LUwkBa4i94QVf4jfP9dcT6DeuPCvYzAJpn2i3L5w

http://explorer.solana.com/transactions/2gdft9V1irmxCz9k9on7mss5ey3kZMnpuGJNHv52F8FSNBQyWRkeCmo5oB2RMm3CEhRQUvrFFLE59JY2bfvTgtxF

**Comment by danpaul000** [comment] 2020-04-29 19:56
> Two more transactions, with this error, that **didn't** go through:
> 
> http://explorer.solana.com/transactions/5beS2EMnHurQXmQzkTZiLqx2bKWkp9CYeCPKJ5CRCnismqG6LUwkBa4i94QVf4jfP9dcT6DeuPCvYzAJpn2i3L5w
> 
> http://explorer.solana.com/transactions/2gdft9V1irmxCz9k9on7mss5ey3kZMnpuGJNHv52F8FSNBQyWRkeCmo5oB2RMm3CEhRQUvrFFLE59JY2bfvTgtxF

@ericlwilliams what you saw was actually my mis-interpretation of the output of our ledger display tool.  I thought certain transactions were confirmed when they were not.  I added this feature request which would eliminate the issue you are referring to here (https://github.com/solana-labs/solana/issues/9798).   This issue is in scope only of the transactions that DID go through, but showed the error as well.

**Comment by mvines** [comment] 2020-05-01 03:34
This has probably been fixed by https://github.com/solana-labs/solana/pull/9792, we're now just waiting for a bit more feedback to confirm

**Comment by mvines** [comment] 2020-05-06 16:00
Calling this done.  If it reproduces on mainnet-beta please re-open

**Closed by mvines** 2020-05-06 16:00 UTC
