### ISSUE TITLE
Throw a custom `Error` subclass in web3.js when blocks are not available (calling `getBlock`)

### ISSUE THREAD

**Issue by kelvinwop** [solana-labs/solana#26632] opened 2022-07-15 00:17 UTC
#### Problem
in @solana/web3.js:

Error: failed to get confirmed block: Block not available for slot 141622502
    at Connection.getBlock (xxxx\node_modules\@solana\web3.js\lib\index.cjs.js:6688:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ScanBlock (xxxx\src\services\blockScraping.js:129:16)

I get this error when calling **getBlock**

not really a problem cool. The problem is the error.name = Error

#### Proposed Solution

please make a specific error for this error

**Comment by steveluscher** [comment] 2022-07-16 04:44
Duplicate of #11963.

**Closed by steveluscher** 2022-07-16 04:44 UTC
