### ISSUE TITLE
Consider adding timestamps to explorer transaction history

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#12963] opened 2020-10-19 02:46 UTC
Slot is interesting, but more interesting and helpful for users would be the block time:
![image](https://user-images.githubusercontent.com/1281082/96395823-77e34f00-117a-11eb-9856-05054306d2f9.png)

**Comment by jstarry** [comment] 2020-10-19 09:40
Dupe of https://github.com/solana-labs/solana/issues/12236

**Closed by jstarry** 2020-10-19 09:40 UTC
