### ISSUE TITLE
`solana-keygen -o` silently creates files in ~ if it can't write to the current directory

### ISSUE THREAD

**Issue by tredondo** [solana-labs/solana#20422] opened 2021-10-04 20:01 UTC
#### Problem
Assume the user doesn't have write permissions to the current directory. Executing `solana-keygen new --no-passphrase -o ./not-here.json` will display `Wrote new keypair to ./not-here.json`. That is incorrect. The file isn't in the current directory. It's actually at `~/not-here.json`.

Repeating the command will show "Refusing to overwrite ./not-here.json without --force flag".

Passing the full path to the file does result in the correct error:

```
$ solana-keygen new --no-passphrase -o $PWD/not-here.json
Generating a new keypair
Error: Unable to write /home/tredondo/solana/not-here.json: Permission denied (os error 13)
```

#### Proposed Solution

Fully resolve the path to the output file.

**Comment by kopeboy** [comment] 2022-04-15 09:03
Having the same issue on macOS 12.3, with solana v1.10.8
`solana-keygen new -o ~/Users/kopeboy/.config/solana/id.json                                       
Refusing to overwrite /Users/kopeboy/Users/kopeboy/.config/solana/id.json without --force flag`
Can confirm the error wasn't even showing when run the first time following official example program docs.

**Comment by steviez** [comment] 2022-04-18 07:06
> Can confirm the error wasn't even showing when run the first time

So it sounds like the first time you successfully created a key, and subsequent runs are failing because you're trying to write a key to an existing file (which would overwrite the existing key). Protecting against an accidental overwrite is expected behavior / safer.

```
$ solana-keygen new -o ./keypair.json --no-bip39-passphrase

Generating a new keypair
Wrote new keypair to ./keypair.json
...
$ solana-keygen new -o ./keypair.json --no-bip39-passphrase

Refusing to overwrite ./keypair.json without --force flag
```

@kopeboy - I answered here because this was such a quick thing, but for future "support" issues, please join us on [Discord](https://discord.com/invite/pquxPsq).

Going to close this issue given that I was unable to reproduce and that the original filer never responded.

**Closed by steviez** 2022-04-18 07:06 UTC

**Comment by tredondo** [comment] 2022-04-18 08:14
Sorry, `solana-keygen 1.6.27 (src:c5d174c1; feat:1203293006)`.

**Comment by steviez** [comment] 2022-04-19 02:35
> Sorry, `solana-keygen 1.6.27 (src:c5d174c1; feat:1203293006)`.

Hmm, would you care to try with a newer version such as `v1.9.16`:
https://github.com/solana-labs/solana/releases/tag/v1.9.16

**Comment by tredondo** [comment] 2022-04-19 10:37
Still happens with v1.9.6, but only in conjunction with firejail (which I realized was the use case with v1.6.27 as well).

If I run the binary directly, it correctly fails to write in that directory:

```
$ /usr/bin/solana-keygen new --no-passphrase -o ./never-here.json
Generating a new keypair
Error: Unable to write ./never-here.json: Permission denied (os error 13)
```

Probably out of scope, though it's interesting that @kopeboy saw the same error.

**Comment by steviez** [comment] 2022-04-19 16:40
> but only in conjunction with firejail (which I realized was the use case with v1.6.27 as well).
>
> If I run the binary directly, it correctly fails to write in that directory:

Cool, at least we can explain the difference in behavior

> Probably out of scope

Yeah, we're happy to review a PR if you look into it, but I don't think we'll be putting any time/effort into this at the moment

> though it's interesting that @kopeboy saw the same error.

We'd need kopeboy to confirm, but from their comment, I believe their issue is different than yours. From the comment, I think kopeboy had written a key to somewhere on disk (that they had permission to write to), and then ran the same command which would try to write a new key on top of the already written disk. The tool raises an error for that to avoid accidentally overwriting the preexisting key

**Comment by miguelgargallo** [comment] 2022-06-08 11:28
This happens because of:
miguelgargallo@canarchain:~/.config/solana$ solana config set --url https:/api.devnet.solana.com
miguelgargallo@canarchain:~/.config/solana$ solana airdrop 10 someaddreshere
miguelgargallo@canarchain:~/.config/solana$ solana balance
0 SOL
miguelgargallo@canarchain:~/.config/solana$ solana balance
0 SOL
miguelgargallo@canarchain:~/Desktop$ cd
miguelgargallo@canarchain:~$ solana balance
Error: Dynamic program error: No default signer found, run "solana-keygen new -o id.json" to create a new one

I am on Ubuntu 22.04 LTS Latest version of Solana at that moment

**Comment by miguelgargallo** [comment] 2022-06-08 12:22
> This happens because of: miguelgargallo@canarchain:-/.config/solana$ solana config set --url https:/api.devnet.solana.com miguelgargallo@canarchain:-/.config/solana$ solana airdrop 10 someaddreshere miguelgargallo@canarchain:-/.config/solana$ solana balance 0 SOL miguelgargallo@canarchain:-/.config/solana$ solana balance 0 SOL miguelgargallo@canarchain:-/Desktop$ cd miguelgargallo@canarchain:-$ solana balance Error: Dynamic program error: No default signer found, run "solana-keygen new -o id.json" to create a new one
> 
> I am on Ubuntu 22.04 LTS Latest version of Solana at that moment

The thing is that we change the network type and so returning to the mainnet, would solve the problem, I will try now and comeback

**Comment by miguelgargallo** [comment] 2022-06-08 12:26
> > This happens because of: miguelgargallo@canarchain:-/.config/solanasolanaconfigset−−urlhttps:/api.devnet.solana.commiguelgargallo@canarchain:−/.config/solana solana airdrop 10 someaddreshere miguelgargallo@canarchain:-/.config/solanasolanabalance0SOLmiguelgargallo@canarchain:−/.config/solana solana balance 0 SOL miguelgargallo@canarchain:-/Desktopcdmiguelgargallo@canarchain:− solana balance Error: Dynamic program error: No default signer found, run "solana-keygen new -o id.json" to create a new one
> > I am on Ubuntu 22.04 LTS Latest version of Solana at that moment
> 
> The thing is that we change the network type and so returning to the mainnet, would solve the problem, I will try now and comeback

Effectively immediate everything returns to its normal state:

miguelgargallo@canarchain:path$ solana config set --url https://api.mainnet-beta.solana.com
Config File: path
RPC URL: https://api.mainnet-beta.solana.com
WebSocket URL: wss://api.mainnet-beta.solana.com/ (computed)
Keypair Path: id.json
Commitment: confirmed
miguelgargallo@canarchain:~/path$ solana balance
0.MYbalanceISvisible SOL
miguelgargallo@canarchain:~/path$

**Comment by miguelgargallo** [comment] 2022-06-08 12:40
This happens because @kopeboy, @tredondo @steviez or the user changed to devnet to request an airdrop or something else.

**Error Replication**

miguelgargallo@canarchain:-/.path$/solana$ solana config set --url https:/api.devnet.solana.com
miguelgargallo@canarchain:-/.path$/solana$ solana airdrop 10 someaddreshere
miguelgargallo@canarchain:-/.path$/solana$ solana balance
0 SOL
miguelgargallo@canarchain:-/.path$/solana$ solana balance
0 SOL
miguelgargallo@canarchain:-/Desktop$ cd
miguelgargallo@canarchain:-$ solana balance
Error: Dynamic program error: No default signer found, run "solana-keygen new -o id.json" to create a new one


Regarding my setup:
Ubuntu 22.04 LTS
solana-cli 1.10.24

**Proposed Solution**

Returning to the mainnet, would solve the problem:

Effectively immediate everything returns to its normal state:

miguelgargallo@canarchain:-/.path$/solana$ solana config set --url https://api.mainnet-beta.solana.com
Config File: path
RPC URL: https://api.mainnet-beta.solana.com
WebSocket URL: wss://api.mainnet-beta.solana.com/ (computed)
Keypair Path: id.json
Commitment: confirmed
miguelgargallo@canarchain:-/.path$/solana$ solana balance
0.XYZWQRCSP SOL
