### ISSUE TITLE
accounts_db assert in shrink_all_slots

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#16466] opened 2021-04-10 19:49 UTC
#### Problem

Reported crash on discord 1.5.18:
https://discord.com/channels/428295358100013066/689412830075551748/829749233585356833

```
Apr  8 14:42:56 mercury validator.sh[3593]: [2021-04-08T13:42:56.576077250Z INFO  solana_metrics::metrics] datapoint: shrink_stats num_slots_shrunk=11285i storage_read_elapsed=0i index_read_elapsed=299697i find_alive_elapsed=1595i create_and_insert_store_elapsed=139751i store_accounts_elapsed=71675i update_index_elapsed=153802i handle_reclaims_elapsed=73842i write_storage_elapsed=169i rewrite_elapsed=466232i drop_storage_entries_elapsed=1i recycle_stores_write_time=0i accounts_removed=47940i bytes_removed=17014784i
Apr  8 14:42:57 mercury validator.sh[3593]: thread 'main' panicked at 'assertion failed: same_slot_previous_updates.len() <= 1', runtime/src/accounts_index.rs:158:9
Apr  8 14:42:57 mercury validator.sh[3593]: stack backtrace:
Apr  8 14:42:57 mercury validator.sh[3593]:    0: std::panicking::begin_panic
Apr  8 14:42:57 mercury validator.sh[3593]:    1: solana_runtime::accounts_index::<impl solana_runtime::accounts_index::ouroboros_impl_write_account_map_entry::WriteAccountMapEntry<T>>::update
Apr  8 14:42:57 mercury validator.sh[3593]:    2: solana_runtime::accounts_index::AccountsIndex<T>::upsert
Apr  8 14:42:57 mercury validator.sh[3593]:    3: solana_runtime::accounts_db::AccountsDb::store_accounts_custom
Apr  8 14:42:57 mercury validator.sh[3593]:    4: solana_runtime::accounts_db::AccountsDb::shrink_all_slots
Apr  8 14:42:57 mercury validator.sh[3593]:    5: solana_runtime::bank::Bank::verify_snapshot_bank
Apr  8 14:42:57 mercury validator.sh[3593]:    6: solana_runtime::snapshot_utils::bank_from_archive
Apr  8 14:42:57 mercury validator.sh[3593]:    7: solana_ledger::bank_forks_utils::load
Apr  8 14:42:57 mercury validator.sh[3593]:    8: solana_core::validator::Validator::new
Apr  8 14:42:57 mercury validator.sh[3593]:    9: solana_validator::main
Apr  8 14:42:57 mercury validator.sh[3593]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Apr  8 14:42:57 mercury validator.sh[3593]: [2021-04-08T13:42:57.751709459Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'assertion failed: same_slot_previous_updates.len() <= 1', runtime/src/accounts_index.rs:158:9" location="runtime/src/accounts_index.rs:158:9"
Apr  8 14:42:57 mercury validator.sh[3593]: [2021-04-08T13:42:57.751738875Z INFO  solana_metrics::metrics] submitting 9 points
Apr  8 14:42:58 mercury systemd[1]: solana.service: Main process exited, code=exited, status=1/FAILURE
```

#### Proposed Solution

Debug and fix.

**Comment by brooksprumo** [comment] 2021-11-17 16:24
I'm going to close this issue as "not reproducible" anymore. Looks like this has been refactored a few times since v1.5.18, and the assert still exists in master here: https://github.com/solana-labs/solana/blob/c3e5927d166a383227f26ebdcc1c6843e47ee247/runtime/src/in_mem_accounts_index.rs#L435-L437
Since shrink happens all the time, we will trip this assert if there is still an underlying bug. Please reopen if this doesn't sound good, or if the bug reappears!

**Closed by brooksprumo** 2021-11-17 16:24 UTC
