### ISSUE TITLE
RPC PubSub/confirmTransaction is unreliable with confirmed/singleGossip

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#15461] opened 2021-02-22 06:52 UTC
#### Problem

Clients currently don't have nice and reliable way to follow updates to given subset's accounts.

Usually, PRC PubSub is the most straightforward solution; but we have some reports PubSub and confirmTransaction misses updates when used with commitment=confirmed/singleGossip.

It seem that the root problem is that we don't reliably send subscription notifications for that commitment level.

Also, this might be related to this old issue: https://github.com/solana-labs/solana/issues/9909

#### Proposed Solution

Debug and fix it.

At least, provide some actionable work-around as a documentation.

CC: @jstarry @CriesofCarrots

**Comment by carllin** [comment] 2021-02-23 10:57
hmm @CriesofCarrots  is it possible here: https://github.com/solana-labs/solana/blob/master/core/src/optimistically_confirmed_bank_tracker.rs#L115-L119 that the root bank is set, purges the optimistically confirmed bank from BankForks, and then this check returns false?

**Comment by CriesofCarrots** [comment] 2021-02-23 17:46
@jstarry , when you have a chance, could you add some detail here from your research on this issue? I think you said the nodes in question were unhealthy and you were not able to reproduce this issue once they had been rebooted.

**Comment by CriesofCarrots** [comment] 2021-02-23 21:26
Regarding question above, adding a counter to see how often this occurs: https://github.com/solana-labs/solana/pull/15492

**Comment by CriesofCarrots** [comment] 2021-10-05 16:12
I believe this was fixed in https://github.com/solana-labs/solana/pull/19092

**Closed by CriesofCarrots** 2021-10-05 16:12 UTC
