### ISSUE TITLE
Initial Snapshot Creation Failing

### ISSUE THREAD

**Issue by ek1977** [solana-labs/solana#7296] opened 2019-12-05 18:51 UTC
#### Problem
I am trying to get a validator node running with the --no-voting flag to generate a complete copy of the blockchain.  However when I initiate the solana-validator program I am getting an error about being unable to move the snapshots.  I am using v0.21.0. 

When I go to the folder where the snapshots are being moved to it looks like the move is actually successful.  This may be related to https://github.com/solana-labs/solana/issues/7258

This is only happening when the --ledger is **not** ~/validator-config

#### Backtrace
~~~~
[2019-12-05T18:37:17.833000040Z WARN  solana_runtime::accounts_db] AccountsDB error: "Unable to move \"/nodedata/solana/validator-config/snapshot/.tmps3JiWt/accounts/1562916.1583515\" to \"/nodedata/solana/validator-config/accounts\": other os error"
thread 'main' panicked at 'Load from snapshot failed: IO(Custom { kind: Other, error: "Unable to move \"/nodedata/solana/validator-config/snapshot/.tmps3JiWt/accounts/1562916.1583515\" to \"/nodedata/solana/validator-config/accounts\": other os error" })', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  12: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  13: rust_begin_unwind
             at src/libstd/panicking.rs:307
  14: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  15: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  16: solana_ledger::bank_forks_utils::load
  17: solana_core::validator::new_banks_from_blocktree
  18: solana_core::validator::Validator::new
  19: solana_validator::main
  20: std::rt::lang_start::{{closure}}
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  24: std::panicking::try
             at src/libstd/panicking.rs:271
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  27: main
  28: __libc_start_main
  29: _start
~~~~

**Comment by mvines** [comment] 2019-12-07 21:12
Yep this is a duplicate of #7258

**Closed by mvines** 2019-12-07 21:12 UTC
