### ISSUE TITLE
address verify is not strict enough

### ISSUE THREAD

**Issue by liyanhrxy** [solana-labs/solana#18032] opened 2021-06-17 02:46 UTC
#### Problem
`7aXrw7nxSKijdToRuWUGG3gZ1qB3M59xTxAEn879fD6Y` and `7aXrw7nxSKijdToRuWUGG3gZ1qB3M59xTxAEn879fD6` which is a substring of first , but they are valid by current  verify logic(the trouble with base58, why not base58check???) !!!!!!! 

#### Proposed Solution
add other check in verify logic

**Comment by t-nelson** [comment] 2021-06-17 03:33
Hi!  Thanks for reporting.  This is a duplicate of https://github.com/solana-labs/solana/issues/6970

**Closed by t-nelson** 2021-06-17 03:33 UTC
