### ISSUE TITLE
Using pubsub to confirm transactions is not compatible with v1.3

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#12117] opened 2020-09-08 18:36 UTC
#### Problem

The latest web3.js  (v0.73.0) is not compatible with Solana v1.3:

```
(node:15856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Running `npm run test:live` against v1.3 to recreate

FYI @jstarry

**Comment by jstarry** [comment] 2020-09-09 02:26
@jackcmay the issue was likely due to a regression on v1.3 where the rpc pubsub service would panic on certain subscriptions. This was fixed in v1.3.9 and I just confirmed that `npm run test:live` works against that version

**Closed by jstarry** 2020-09-09 02:26 UTC
