### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by wangweiwei1188** [solana-labs/solana#24218] opened 2022-04-09 01:28 UTC
#### Problem
Now, I want to download the windows version  according to[Download the binaries by navigating to https://github.com/solana-labs/solana/releases/latest, download solana-release-x86_64-pc-windows-msvc.tar.bz2, then extract the archive using WinZip or similar.]
But, I can't find it.

**Comment by steviez** [comment] 2022-04-09 02:12
Duplicate of https://github.com/solana-labs/solana/issues/24092

**Closed by steviez** 2022-04-09 02:12 UTC
