### ISSUE TITLE
solana-test-validator --warp-slot has limited time progression

### ISSUE THREAD

**Issue by RuvenSalamon** [solana-labs/solana#24699] opened 2022-04-26 15:57 UTC
#### Problem
When I use the `--warp-slot` option on the `solana-test-validator`  I can successfully warp my local test validator to a certain slot, however, the block time never goes beyond approximately 25h (+- 93109 seconds) into the future. Doesn't matter how much forward I warp.

#### Proposed Solution
The warp-slot option doesn't have this restriction.

**Comment by t-nelson** [comment] 2022-04-26 21:14
duplicate of https://github.com/solana-labs/solana/issues/19822

**Closed by t-nelson** 2022-04-26 21:14 UTC
