### ISSUE TITLE
web3.js: partialSign breaks deserialized transactions

### ISSUE THREAD

**Issue by coffeemug** [solana-labs/solana#20743] opened 2021-10-16 20:58 UTC
#### Problem

Whenever `partialSign` is applied to a transaction that's been previously partially signed, serialized, and deserialized, it clears all existing signatures on the transaction:

```js
const tx = new Transaction();
...
tx.partialSign(signer);

const deserializedTx = Transaction.from(tx.serialize({ requireAllSignatures: false }));
deserializedTx.partialSign(anotherSigner); // broken, clears `signer`
```

I tried various workarounds, for example taking signatures from `tx` and manually applying them to `deserializedTx`, but doing it that way causes validation of those signatures to fail. This means it's not possible to apply `partialSign`/`addSignature` to transactions that have been deserialized from the wire, which is a serious limitation.

Could someone recommend a workaround for this?

**Comment by MirekR** [comment] 2021-12-15 09:50
We're having same issue, have you been able to get around it?

**Comment by MirekR** [comment] 2021-12-16 09:08
For anyone who's interested in, we had some success with the below:

```
  const transactionHash = "YOUR_TRANSACTION_HASH";

  // THIS IS TO SIMULATE WEB
  const rawTransaction = Buffer.from(transactionHash, 'base64');
  const newTrx = web3.Transaction.from(rawTransaction);

  console.log(`Transaction before partial sign ${JSON.stringify(newTrx)}`)

  // make sure we have immutable array
  const originalSignatures  = Object.assign([], newTrx.signatures) as web3.SignaturePubkeyPair[];
  const filteredSignatures = originalSignatures.filter(item => item.signature != null);

  console.log(`Original signatures are ${JSON.stringify(originalSignatures)}`);

  newTrx.partialSign(buyer);

  filteredSignatures.forEach(sign => {
      newTrx.addSignature(sign.publicKey, sign.signature as Buffer);
  });

  console.log("=============================================================");
  console.log(`After add ${JSON.stringify(newTrx.signatures)}`);
  
  const serialTx = newTrx.serialize(
    {
      requireAllSignatures: false,
      verifySignatures: false,
    }
  );
  
  console.log("=============================================================");
  console.log(`Full transaction ${JSON.stringify(web3.Transaction.from(serialTx))}`)

  const id = await web3.sendAndConfirmRawTransaction(connection, serialTx, {skipPreflight: true});
  

  console.log(`Complete transaction: ${id}`);
```

In general, the problem seems to be with deserialization, where Typescript is loosing it's types and then methods start returning incorrect values, as example Keypair.publicKey.toString() after serialization stops returning base encoded string but returnes "[object object]"

**Comment by bmeeder22** [comment] 2022-03-03 18:07
We were having success with this code block as well and is no longer working ^

**Comment by bmeeder22** [comment] 2022-03-03 20:10
This was working in @solana/web3.js version 1.31.0 and in all higher versions the workaround is broken. I believe this is due to this commit: https://github.com/solana-labs/solana-web3.js/commit/410780a41bbffb556e1d1f53d097934ffb56870f

**Comment by bmeeder22** [comment] 2022-03-03 20:29
Update the following code is working for me in @solana/web3 versions higher than `1.31.0`

```
function partialSignDeserializedTx(rawTx, partialSignersArr) {
  const newTrx = Transaction.from(rawTx);

  // make sure we have immutable array
  const originalSignatures = Object.assign([], newTrx.signatures);
  const filteredSignatures = originalSignatures.filter(
    (item) => item.signature != null
  );

  filteredSignatures.forEach((sign) => {
    console.log(sign.publicKey.toString());
    newTrx.addSignature(sign.publicKey, sign.signature);
  });

  newTrx.partialSign(...partialSignersArr);
  return newTrx.serialize({
    requireAllSignatures: true,
    verifySignatures: true,
  });
}
```

Needed to swap the order of addingSignature and partialSigning since now it sorts and expects the payer signature to be first in the list.

**Comment by jordansexton** [comment] 2022-03-30 20:36
This is caused by https://github.com/solana-labs/solana/issues/21722. Closing as a duplicate, but this should be fixed by https://github.com/solana-labs/solana/pull/23720 soon.

**Comment by jordansexton** [comment] 2022-03-31 04:07
Actually, I'm going to reopen this until it's confirmed to be fixed by #23720 as well.

**Comment by jordansexton** [comment] 2022-04-16 20:45
#23720 has been merged and published in `@solana/web3.js@1.39.1`. Can you confirm if it fixes your issue?

**Comment by z3000z3000z3000** [comment] 2022-04-18 14:35
> This was working in @solana/web3.js version 1.31.0 and in all higher versions the workaround is broken. I believe this is due to this commit: [solana-labs/solana-web3.js@410780a](https://github.com/solana-labs/solana-web3.js/commit/410780a41bbffb556e1d1f53d097934ffb56870f)

Maybe revert it?


As soon as serialize/deserialize problem was solved by https://github.com/solana-labs/solana/pull/23720 ?

**Comment by metapirate0311** [comment] 2022-06-23 02:37
> For anyone who's interested in, we had some success with the below:
> 
> ```
>   const transactionHash = "YOUR_TRANSACTION_HASH";
> 
>   const rawTransaction = Buffer.from(transactionHash, 'base64');
>   const newTrx = web3.Transaction.from(rawTransaction);
> 
>   console.log(`Transaction before partial sign ${JSON.stringify(newTrx)}`)
> 
>   // make sure we have immutable array
>   const originalSignatures  = Object.assign([], newTrx.signatures) as web3.SignaturePubkeyPair[];
>   const filteredSignatures = originalSignatures.filter(item => item.signature != null);
> 
>   console.log(`Original signatures are ${JSON.stringify(originalSignatures)}`);
> 
>   newTrx.partialSign(buyer);
> 
>   filteredSignatures.forEach(sign => {
>       newTrx.addSignature(sign.publicKey, sign.signature as Buffer);
>   });
> 
>   console.log("=============================================================");
>   console.log(`After add ${JSON.stringify(newTrx.signatures)}`);
>   
>   const serialTx = newTrx.serialize(
>     {
>       requireAllSignatures: false,
>       verifySignatures: false,
>     }
>   );
>   
>   console.log("=============================================================");
>   console.log(`Full transaction ${JSON.stringify(web3.Transaction.from(serialTx))}`)
> 
>   const id = await web3.sendAndConfirmRawTransaction(connection, serialTx, {skipPreflight: true});
>   
> 
>   console.log(`Complete transaction: ${id}`);
> ```

Could you post the completed code here agian?

**Comment by steveluscher** [comment] 2022-11-17 16:53
Closing this on the basis of #23720 having been merged; please reopen if there's more work to be done!

**Closed by steveluscher** 2022-11-17 16:53 UTC

**Comment by shirecoding** [comment] 2024-01-24 14:27
I have the opposite error. signTransactions removes the partialSigned. This is a problem because wallet adaptors can't partial sign, they can only sign, which removes any partial sign done in a backend server.

I had to do the opposite, sign using the wallet adapter, then serialize the transaction send it over to the backend, and then the backend partial signs using a private key and sends the transaction

I can't do it the other way around, eg. i always have to end with partial sign and not sign. Because sign removes partial sign, which means i want have the wallet adaptor which does not have partial sign be the last.

Am am i getting something wrong?

**Comment by CriesofCarrots** [comment] 2024-01-24 16:29
@shirecoding , please don't necropost. The web3.js code isn't in this repository anymore 😞 
Also, developer questions should go to [Solana Stack Exchange](https://solana.stackexchange.com/)
