### ISSUE TITLE
Solana web3.js library incorrectly encodes AccountMeta if there are multiple accounts with the same pubkey

### ISSUE THREAD

**Issue by bji** [solana-labs/solana#23641] opened 2022-03-14 08:01 UTC
#### Problem

This code in web3.js transaction.ts file:

``` const accountKeys = signedKeys.concat(unsignedKeys);
    const instructions: CompiledInstruction[] = this.instructions.map(
      instruction => {
        const {data, programId} = instruction;
        return {
          programIdIndex: accountKeys.indexOf(programId.toString()),
          accounts: instruction.keys.map(meta =>
            accountKeys.indexOf(meta.pubkey.toString()),
          ),
          data: bs58.encode(data),
        };
      },
    );
```
    (currently line 345 of transacton.ts)

is incorrect.  If the transaction has the same pubkey listed twice in the message header:

- One as signer, read-write
- Once as signer, read-only

Then the above code will always select the index of the signer, read-write account reference, even if the AccountMeta in the instruction itself (i.e. the account as listed in the instruction accounts list) is signer, read-only.  This is because the function passed to map just looks up the accountKeys.indexOf(meta.pubkey.toString()) and does not consider the flags on the AccountMeta.

I have an on-chain program that inspects the account metas in the instruction params and enforces that the signer and writable flags are set to exactly the expected values.  But the transaction is encoded incorrectly by web3.js as I just described, and my program fails with an error because it is being given a signer, read-write account meta, not a signer, read-only as it should be, because the signer, read-write was found "first" by the map code when the instruction was encoded.

(in other words, the keys[] I am giving to the instruction include an AcountMeta that is signer, read-only; but the transaction is being encoded with a reference to an index from the message header accounts list that is the signer, **read-write** account, which is not the account that I specified at that position in the instruction accountmetas list)

#### Proposed Solution

I am not that familiar with javascript so I can't offer specific code examples.  But I can say that the code I quoted needs to be modified to, instead of using account.indexOf(), do a more thorough search for the account that both has the correct pubkey *and* the correct flags (signer and/or writable, whatever matches what's in the meta).

**Comment by t-nelson** [comment] 2022-03-14 16:26
Account metas are encoded transaction-wide and each account receives the highest promoted position.  Consider the [`MessageHeader`](https://github.com/solana-labs/solana/blob/63bf0f66af8c3dbe75c92726571f6f82560c839b/sdk/program/src/message/mod.rs#L92-L108), which declares ranges in the `account_keys` vector

**Comment by jordansexton** [comment] 2022-03-17 01:09
Duplicate of #23631

**Comment by bji** [comment] 2022-03-17 01:13
Sorry I missed your previous comment.

Why is "each account receives the highest promoted position" the correct behavior?

**Comment by bji** [comment] 2022-03-17 01:13
Also why are AccountMetas encoded transaction wide?  Each instruction has its own account metas and should be able to have a different set than other instructions within the same transaction.

**Closed** 2022-03-17 01:14 UTC
