### ISSUE TITLE
Solana Program Close Does Not Respect "--authority"

### ISSUE THREAD

**Issue by sol-mocha** [solana-labs/solana#33171] opened 2023-09-06 18:33 UTC
#### Problem

With Version `solana-cli 1.16.10 (src:382b3f16; feat:3712769919, client:SolanaLabs`

According to the `solana program close --help`, the `--authority` is a valid option.

```
--authority <AUTHORITY_SIGNER>     Upgrade or buffer authority [default: the default configured keypair]
```

The following command does not work as expected, and times out.
Command: 
```
 solana program close --bypass-warning --authority ./upgrade-authority.json <Address>
```
Output: 
```
Error: Close failed: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds
```

Once that failed I set the `upgrade-authority.json` as my default keypair, after which the following command **did** work.

```
solana program close --bypass-warning <Address>
```

#### Proposed Solution

- Display the publickey that is signing the transaction in the console output as confirmation to know that the correct key is being used
- Respect the `authority` command that is shown in the `--help` docs of the `solana program close` command.

**Comment by joncinque** [comment] 2023-09-27 13:47
Sorry, I wasn't able to reproduce this. Against a local validator, I ran:

```
$ solana program deploy program.so
 # note the program id, which was HAUbf6xjvCZT8VZ6iwxJZNMKxiDB17UyxhKPoBvLPLjf,
$ solana-keygen new -o test.json
$ solana program set-upgrade-authority HAUbf6xjvCZT8VZ6iwxJZNMKxiDB17UyxhKPoBvLPLjf --new-upgrade-authority test.json
$ solana program close HAUbf6xjvCZT8VZ6iwxJZNMKxiDB17UyxhKPoBvLPLjf --bypass-warning --authority test.json
Closed Program Id HAUbf6xjvCZT8VZ6iwxJZNMKxiDB17UyxhKPoBvLPLjf, 7.21722072 SOL reclaimed
```

I tested this with 1.16.13 and master, and both worked. Perhaps this was broken in a previous release. Either way, I put in #33426 to surface the error immediately by performing preflight checks.

**Comment by CriesofCarrots** [comment] 2023-12-20 21:41
Since Jon wasn't able to reproduce this error, I'm closing the issue. Feel free to reopen if the bug recurs.

**Closed by CriesofCarrots** 2023-12-20 21:41 UTC
Labels: community
