### ISSUE TITLE
float methods (trunc,ceil,floor) may compile to unknown syscalls

### ISSUE THREAD

**Issue by kodemartin** [solana-labs/solana#25158] opened 2022-05-12 11:15 UTC
#### Problem

When trying to execute some common float operations ([trunc][], [ceil][],[floor][]), on occasion we get the following error from bpf-builder
```sh
cargo-build-bpf child:
/home/kde/.local/share/solana/install/releases/stable-59a58f6716bd12fb262a5ca163b658b6606edc26/solana-release/bin/sdk/bpf/scripts/strip.sh
/home/kde/projects/solana/float_bug/target/bpfel-unknown-unknown/release/float_bug.so
/home/kde/projects/solana/float_bug/target/deploy/float_bug.so
cargo-build-bpf child:
/home/kde/.local/share/solana/install/releases/stable-59a58f6716bd12fb262a5ca163b658b6606edc26/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf
--dyn-symbols /home/kde/projects/solana/float_bug/target/deploy/float_bug.so
Warning: the following functions are undefined and not known syscalls ["trunc"].
         Calling them will trigger a run-time error.
```
When trying to call the respective instruction the transaction fails.

##### How to reproduce

* Create a new minimal project from the following template

   ```sh
   $ git clone git@github.com:mvines/solana-bpf-program-template.git float_bug
   ```

* Copy and paste the following `process_instruction` function in `src/lib.rs`

  ```rust
    entrypoint!(process_instruction);
    fn process_instruction(
        program_id: &Pubkey,
        accounts: &[AccountInfo],
        instruction_data: &[u8],
    ) -> ProgramResult {
        msg!(
            "process_instruction: {}: {} accounts, data={:?}",
            program_id,
            accounts.len(),
            instruction_data
        );
        let a = 3_000_f64;
        msg!("truncating {}: {:?}", a, a.trunc());
        msg!("truncating {}: {:?}", a, a.trunc());
        Ok(())
    }
  ```

* Run `cargo build-bpf`

##### Additional remarks

* This variation works

  ```rust
    entrypoint!(process_instruction);
    fn process_instruction(
        program_id: &Pubkey,
        accounts: &[AccountInfo],
        instruction_data: &[u8],
    ) -> ProgramResult {
        msg!(
            "process_instruction: {}: {} accounts, data={:?}",
            program_id,
            accounts.len(),
            instruction_data
        );
        let a = 3_000_f64;
        msg!("truncating {}: {:?}", a, a.trunc());
        Ok(())
    }
  ```
  which implies that the problem appears after **copying** the value.

* Another variation that fails and illustrates the correlation with copy operations

  ```rust
    entrypoint!(process_instruction);
    fn process_instruction(
        program_id: &Pubkey,
        accounts: &[AccountInfo],
        instruction_data: &[u8],
    ) -> ProgramResult {
        msg!(
            "process_instruction: {}: {} accounts, data={:?}",
            program_id,
            accounts.len(),
            instruction_data
        );
        let a = 3_000_f64;
        // This message appears in error tracebacks
        msg!("truncating {}: {:?}", a, a.trunc());
        let b = a;
        msg!("{}", a);
        msg!("{}", b);
        msg!("truncating {}: {:?}", a, a.trunc());
        Ok(())
    }
  ```

[trunc]: https://doc.rust-lang.org/std/primitive.f64.html#method.trunc
[floor]: https://doc.rust-lang.org/std/primitive.f64.html#method.floor
[ceil]: https://doc.rust-lang.org/std/primitive.f64.html#method.ceil

**Comment by jstarry** [comment] 2022-05-12 13:31
cc @Lichtso

**Comment by Lichtso** [comment] 2022-05-12 15:36
@kodemartin Which `bpf_tools_version` are you using?

@alessandrod, This sounds like this is caused by the changes of how we handle dynamic linking and unresolved symbols.

Also @dmakarov updated the Rust to BPF toolchain today: https://github.com/solana-labs/solana/commit/9d18fe019b9cc06386406688295a2389683f09c8

**Comment by alessandrod** [comment] 2022-05-12 22:28
@dmakarov this looks like a build issue in the toolchain, where the float fallbacks haven't been correctly linked in in `compiler-builtins` so they remain unresolved. Then the rbpf message is misleading since we (currently) treat all unresolved symbols as syscalls.

**Comment by dmakarov** [comment] 2022-05-12 23:53
The problem exists with older bpf-tools version too.

**Comment by kodemartin** [comment] 2022-05-13 08:21
> @kodemartin Which `bpf_tools_version` are you using?
> 
```sh
$ cargo build-bpf --version
solana-cargo-build-bpf 1.10.8
bpf-tools v1.23
```

**Comment by dmakarov** [comment] 2022-05-18 00:01
This is fixed in compiler-builtins https://github.com/solana-labs/compiler-builtins/pull/14

**Closed by dmakarov** 2022-05-18 00:01 UTC
Labels: bug
