### ISSUE TITLE
Circular dependency in BPF f32 `pow` implementation

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#15573] opened 2021-02-27 03:07 UTC
#### Problem

The following causes compute budget exhaustion:

```rust
    msg!("pre pow");
    sol_log_compute_units();
    let c = 1_f32.powi(instruction_data[0] as i32);
    msg!("post pow");
    sol_log_compute_units();
    msg!("{}", c);
```

**Comment by dmakarov** [comment] 2021-03-10 17:24
The issue is resolved by upgrading to bpf-tools v1.1 ( https://github.com/solana-labs/solana/pull/15776 )

**Closed by dmakarov** 2021-03-10 17:24 UTC
Labels: bug
