### ISSUE TITLE
solana-keygen new --no-outfile fails on version 1.7.1

### ISSUE THREAD

**Issue by wale-e** [solana-labs/solana#18083] opened 2021-06-19 11:49 UTC
#### Problem
running on command on cli fails
"solana-keygen new --no-outfile" or "solana-keygen new --no-passphrase --no-outfile" on version 1.7.1
issues seems related to --no-outfile flag

#### Proposed Solution
Issue isn't present on 1.6.11

**Comment by CriesofCarrots** [comment] 2021-06-19 16:32
Thanks, duplicate of https://github.com/solana-labs/solana/issues/17860
Fixed in v1.7.2

**Closed by CriesofCarrots** 2021-06-19 16:32 UTC
