### ISSUE TITLE
kin-sim stuck on "Waiting to switch vote..."

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#32250] opened 2023-06-23 15:40 UTC
#### Problem

On kin-sim, we sometimes see that the nodes stuck on "Waiting to switch vote ...".

This happens for several times before. And it happens again for the most recent run at around 8.7B accounts - specifically around slot `2551319 --> 2551320`.

###  slot 2251319  (all 4 nodes replay the bank and compute the same bank hash)
kin1
[2023-06-18T22:51:04.825244479Z INFO  solana_runtime::bank] bank frozen: 2251319 hash: D6AuLLVVA6AbnTKeeihN8q79SxP61jpmQzoT5tqQ5Bb5 accounts_delta: 9rbBUifi5kaL746ZT5MDHbu4h9nJe5QmeiTpcKqK8YZ3 signature_count: 435 last_blockhash: EZuMxFuubZUziUfaetNWoBUFYmdoGHBancpUCTdTFuHt capitalization: 8364699783503611542, stats: BankHashStats { num_updated_accounts: 5637, num_removed_accounts: 0, num_lamports_stored: 203812897707280705, total_data_len: 304615, num_executable_accounts: 0 }

kin2
[2023-06-18T22:51:05.630639428Z INFO  solana_runtime::bank] bank frozen: 2251319 hash: D6AuLLVVA6AbnTKeeihN8q79SxP61jpmQzoT5tqQ5Bb5 accounts_delta: 9rbBUifi5kaL746ZT5MDHbu4h9nJe5QmeiTpcKqK8YZ3 signature_count: 435 last_blockhash: EZuMxFuubZUziUfaetNWoBUFYmdoGHBancpUCTdTFuHt capitalization: 8364699783503611542, stats: BankHashStats { num_updated_accounts: 5637, num_removed_accounts: 0, num_lamports_stored: 203812897707280705, total_data_len: 304615, num_executable_accounts: 0 }

kin3
[2023-06-18T22:51:04.005814036Z INFO  solana_runtime::bank] bank frozen: 2251319 hash: D6AuLLVVA6AbnTKeeihN8q79SxP61jpmQzoT5tqQ5Bb5 accounts_delta: 9rbBUifi5kaL746ZT5MDHbu4h9nJe5QmeiTpcKqK8YZ3 signature_count: 435 last_blockhash: EZuMxFuubZUziUfaetNWoBUFYmdoGHBancpUCTdTFuHt capitalization: 8364699783503611542, stats: BankHashStats { num_updated_accounts: 5637, num_removed_accounts: 0, num_lamports_stored: 203812897707280705, total_data_len: 304615, num_executable_accounts: 0 }

kin4
[2023-06-18T22:51:05.483800648Z INFO  solana_runtime::bank] bank frozen: 2251319 hash: D6AuLLVVA6AbnTKeeihN8q79SxP61jpmQzoT5tqQ5Bb5 accounts_delta: 9rbBUifi5kaL746ZT5MDHbu4h9nJe5QmeiTpcKqK8YZ3 signature_count: 435 last_blockhash: EZuMxFuubZUziUfaetNWoBUFYmdoGHBancpUCTdTFuHt capitalization: 8364699783503611542, stats: BankHashStats { num_updated_accounts: 5637, num_removed_accounts: 0, num_lamports_stored: 203812897707280705, total_data_len: 304615, num_executable_accounts: 0 }

### slot 2251320 (all 4 nodes replay the bank and compute the same bank hash)
(plink -batch sol@kin1 "grep 'bank frozen: 2251320' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:06.351271671Z INFO  solana_runtime::bank] bank frozen: 2251320 hash: 4goxZz8ULq7WMLa3EzPER2aJMuEk29BoZQeVvatVMtrV accounts_delta: 7Vy9pV921ujs75TZ59HUxVyGVK7uhAJ9iCfHT8ZK9FYj signature_count: 107 last_blockhash: 9btJoS11bYWM62tyKcJrvec1iguF1UKahf6iJCE5oHqm capitalization: 8364701033503344042, stats: BankHashStats { num_updated_accounts: 1520, num_removed_accounts: 0, num_lamports_stored: 58777930830541355, total_data_len: 210103, num_executable_accounts: 0 }

(plink -batch sol@kin2 "grep 'bank frozen: 2251320' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:06.181292474Z INFO  solana_runtime::bank] bank frozen: 2251320 hash: 4goxZz8ULq7WMLa3EzPER2aJMuEk29BoZQeVvatVMtrV accounts_delta: 7Vy9pV921ujs75TZ59HUxVyGVK7uhAJ9iCfHT8ZK9FYj signature_count: 107 last_blockhash: 9btJoS11bYWM62tyKcJrvec1iguF1UKahf6iJCE5oHqm capitalization: 8364701033503344042, stats: BankHashStats { num_updated_accounts: 1520, num_removed_accounts: 0, num_lamports_stored: 58777930830541355, total_data_len: 210103, num_executable_accounts: 0 }

(plink -batch sol@kin3 "grep 'bank frozen: 2251320' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:06.031206671Z INFO  solana_runtime::bank] bank frozen: 2251320 hash: 4goxZz8ULq7WMLa3EzPER2aJMuEk29BoZQeVvatVMtrV accounts_delta: 7Vy9pV921ujs75TZ59HUxVyGVK7uhAJ9iCfHT8ZK9FYj signature_count: 107 last_blockhash: 9btJoS11bYWM62tyKcJrvec1iguF1UKahf6iJCE5oHqm capitalization: 8364701033503344042, stats: BankHashStats { num_updated_accounts: 1520, num_removed_accounts: 0, num_lamports_stored: 58777930830541355, total_data_len: 210103, num_executable_accounts: 0 }

(plink -batch sol@kin4 "grep 'bank frozen: 2251320' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:06.271335521Z INFO  solana_runtime::bank] bank frozen: 2251320 hash: 4goxZz8ULq7WMLa3EzPER2aJMuEk29BoZQeVvatVMtrV accounts_delta: 7Vy9pV921ujs75TZ59HUxVyGVK7uhAJ9iCfHT8ZK9FYj signature_count: 107 last_blockhash: 9btJoS11bYWM62tyKcJrvec1iguF1UKahf6iJCE5oHqm capitalization: 8364701033503344042, stats: BankHashStats { num_updated_accounts: 1520, num_removed_accounts: 0, num_lamports_stored: 58777930830541355, total_data_len: 210103, num_executable_accounts: 0 }

### voting for 2251319 (all four nodes vote for 2251319)
(plink -batch sol@kin1 "grep 'voting: 2251319' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:04.825770147Z INFO  solana_core::replay_stage] voting: 2251319 0

(plink -batch sol@kin2 "grep 'voting: 2251319' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:05.631282575Z INFO  solana_core::replay_stage] voting: 2251319 0

(plink -batch sol@kin3 "grep 'voting: 2251319' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:04.006198756Z INFO  solana_core::replay_stage] voting: 2251319 0

(plink -batch sol@kin4 "grep 'voting: 2251319' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:05.484337260Z INFO  solana_core::replay_stage] voting: 2251319 0

### voting for 22513i20 (only two nodes submit votes for 2251320).
(plink -batch sol@kin1 "grep 'voting: 2251320' ~/logs/solana-validator.log.5" )

(plink -batch sol@kin2 "grep 'voting: 2251320' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:06.181760236Z INFO  solana_core::replay_stage] voting: 2251320 0

(plink -batch sol@kin3 "grep 'voting: 2251320' ~/logs/solana-validator.log.5" )

(plink -batch sol@kin4 "grep 'voting: 2251320' ~/logs/solana-validator.log.5" )
[2023-06-18T22:51:06.271803732Z INFO  solana_core::replay_stage] voting: 2251320 0

### Stuck on Waiting to switch vote ...
[2023-06-18T22:51:06.351657243Z INFO  solana_core::cluster_slot_state_verifier] check_slot_agrees_with_cluster() slot: 2251319, root: 2251287, slot_state_update: DuplicateConfirmed(DuplicateConfirmedState { duplicate_confirmed_hash: D6AuLLVVA6AbnTKeeihN8q79SxP61jpmQzoT5tqQ5Bb5, bank_status: Frozen(D6AuLLVVA6AbnTKeeihN8q79SxP61jpmQzoT5tqQ5Bb5) })
[2023-06-18T22:51:06.351690937Z INFO  solana_core::replay_stage] Waiting to switch vote to 2251320,
                            resetting to slot Some(2251324) for now,
                            switch proof stake: 0,
                            threshold stake: 1519996530022.4,
                            total stake: 3999990868480

### Relevant code for submitting votes
https://github.com/solana-labs/solana/blob/master/core/src/replay_stage.rs#L3397

#### Proposed Solution

Debug and fix it.

**Comment by HaoranYi** [comment] 2023-06-23 17:39
Vote history
```
kin1
[2023-06-18T22:51:04.825770147Z INFO  solana_core::replay_stage] voting: 2251319 0
[2023-06-18T22:51:06.122467300Z INFO  solana_core::replay_stage] voting: 2251324 0
[2023-06-18T22:51:06.655902320Z INFO  solana_core::replay_stage] voting: 2251325 0

kin3
[2023-06-18T22:51:04.006198756Z INFO  solana_core::replay_stage] voting: 2251319 0
[2023-06-18T22:51:05.783488169Z INFO  solana_core::replay_stage] voting: 2251324 0
[2023-06-18T22:51:06.196548010Z INFO  solana_core::replay_stage] voting: 2251325 0
[2023-06-18T22:51:06.577621636Z INFO  solana_core::replay_stage] voting: 2251326 0

kin2
[2023-06-18T22:51:04.566660469Z INFO  solana_core::replay_stage] voting: 2251318 0
[2023-06-18T22:51:05.631282575Z INFO  solana_core::replay_stage] voting: 2251319 0
[2023-06-18T22:51:06.181760236Z INFO  solana_core::replay_stage] voting: 2251320 0
[2023-06-18T22:51:07.022229314Z INFO  solana_core::replay_stage] voting: 2251321 0
[2023-06-18T22:51:07.694684423Z INFO  solana_core::replay_stage] voting: 2251322 0
[2023-06-18T22:51:08.824881155Z INFO  solana_core::replay_stage] voting: 2251323 0
[2023-06-18T22:51:10.596786946Z INFO  solana_core::replay_stage] voting: 2251328 0

kin4 
[2023-06-18T22:51:05.484337260Z INFO  solana_core::replay_stage] voting: 2251319 0
[2023-06-18T22:51:06.271803732Z INFO  solana_core::replay_stage] voting: 2251320 0
[2023-06-18T22:51:07.133784795Z INFO  solana_core::replay_stage] voting: 2251325 0


2251319 -- 2251324  (kin1, kin3)
    \
     \
     2251320 (kin2, kin4)
```

**Comment by steviez** [comment] 2023-06-23 19:47
Still looking but here is the leader schedule
```
2251316 - 2251319: kin3
2251320 - 2251323: kin2
2251324 - 2251327: kin3
2251328 - 2251331: kin2
```
kin1 / kin3 / kin4 stopped voting altogether, and had their last vote at slot `2251325` (kin3 voted on `2251326` one more on same fork). Also, extending out the graphic Haoran showed:
```
2251319 -- 2251324 -- 2251325  (kin1, kin3, kin4)
    \
     \
     2251320 (kin2, kin4) -- ... -- 2251323 -- 2251328 -- ...
```
Also, kin4 voted on 2251320 and 2251325 which were different forks ...

**Comment by carllin** [comment] 2023-06-24 01:54
Are all 5 nodes stuck on `Waiting to switch vote to 2251320`? i.e. do you still see these logs after their last vote on `2251325`, a log that looks something like `voting: 2251325`

**Comment by steviez** [comment] 2023-06-24 02:13
> Are all 5 nodes stuck on Waiting to switch vote to 2251320? i.e. do you still see these logs after their last vote on 2251325, a log that looks something like voting: 2251325

There were 4 nodes, but yes,
- kin1/3/4 all show `Waiting to switch vote to 2251323`, which is a descendant of `2251320`
- kin2 continued voting as mentioned

**Comment by steviez** [comment] 2023-06-24 02:33
Here is the mapping from node to pubkey:
```
kin1 ==> 31fxZovs3gBKVVTtC2VJUuKeVoq6mQkLjWnicWhErQ4f
kin2 ==> Edfkf9gpC7KpnkNdKRPmseCtkE1zY8fUVRJMbiLYKKdK
kin3 ==> 2k31vk7hPiu2T9fJzuunc6tmaE57P7wt6tFoGK5A7k47
kin4 ==> 3cVWsRiTXD99BXNhzXs7Gkm3YBhCDrMQWnLern8B7TrD
```
Looking at the ledger, I can see:
- kin1's vote for 2251324 landed in 2251326
- kin1's vote for 2251325 landed in 2251327
- kin3's vote for 2251325 landed in 2251326
- kin3's vote for 2251326 landed in 2251327
- kin4 never landed a vote, and I can see it attempting to refresh (ie instances of `refresh_vote` datapoint)

**Comment by steviez** [comment] 2023-06-24 02:47
Also confirmed that the stake distribution is even with 25% per node:
```
{
  "current": [
    {
      "activatedStake": 999997717120,
      "commission": 100,
      "epochCredits": [ ... ],
      "epochVoteAccount": true,
      "lastVote": 2251284,
      "nodePubkey": "3cVWsRiTXD99BXNhzXs7Gkm3YBhCDrMQWnLern8B7TrD",
      "rootSlot": 2251253,
      "votePubkey": "Dou12zNcGLyDeLcxeRGzQ2xBx1orSWg9AKyuWBgfKREp"
    },
    {
      "activatedStake": 999997717120,
      "commission": 100,
      "epochCredits": [ ... ],
      "epochVoteAccount": true,
      "lastVote": 2251286,
      "nodePubkey": "Edfkf9gpC7KpnkNdKRPmseCtkE1zY8fUVRJMbiLYKKdK",
      "rootSlot": 2251255,
      "votePubkey": "PmXohrohcmtKdeeeYygU4q9wSxujSJLmdVBEbmHhyXa"
    },
    {
      "activatedStake": 999997717120,
      "commission": 100,
      "epochCredits": [ ... ],
      "epochVoteAccount": true,
      "lastVote": 2251285,
      "nodePubkey": "2k31vk7hPiu2T9fJzuunc6tmaE57P7wt6tFoGK5A7k47",
      "rootSlot": 2251254,
      "votePubkey": "DJuHQCQrvPRYhNsqTFyvfEEpzypHdBibeidkL5VqSsCx"
    },
    {
      "activatedStake": 999997717120,
      "commission": 100,
      "epochCredits": [ ... ],
      "epochVoteAccount": true,
      "lastVote": 2251286,
      "nodePubkey": "31fxZovs3gBKVVTtC2VJUuKeVoq6mQkLjWnicWhErQ4f",
      "rootSlot": 2251255,
      "votePubkey": "2TLD7hwoUvxS3ufmUNMsBvfaL8Q3XjhYmbvHJCoEuBke"
    }
  ],
}
```

**Comment by steviez** [comment] 2023-06-24 03:33
@HaoranYi - Can you tell us what the last commit these nodes have from master (I don't see the repos on the machine so appears to have been compiled elsewhere and copied on) ? I see that kin4 didn't land its' initial vote, and I'm wondering if it might have failed to land refresh votes because of the bug described in https://github.com/solana-labs/solana/pull/31879.

**Comment by HaoranYi** [comment] 2023-06-24 17:03
commit db4b76d9e25dc119ca94a751d76079a34bfb8eb8
Author: Jeff Washington (jwash) <jeff.washington@solana.com>
Date:   Tue May 16 09:11:24 2023 -0500

    default to using packed ancient append vec (#31657)

Looks like the branch didn't have the above fix. 

I will try to rebase and restart to see if this is still an issue. 

Thank you all for looking.

**Comment by steviez** [comment] 2023-06-25 16:39
Got it, yeah, rebase to the tip of master would be good so you also pick up https://github.com/solana-labs/solana/pull/31954

> I will try to rebase and restart to see if this is still an issue.

Assume you will be restarting the test cluster, I imagine the cluster would have been able to restart with or without the additional commits I referenced. But, these two extra commits should make the cluster more resilient, and increase the chances of votes landing in the fallback methods if the initial vote does not get picked up

**Comment by carllin** [comment] 2023-06-25 22:46
Yeah I suspect without that fix, votes weren't landing which is why they couldn't agree that `325` was the heaviest fork

**Comment by HaoranYi** [comment] 2023-06-26 17:41
Restarted this morning. So far no "FailedSwitchThreshold" at all. Everything looks good.

**Comment by steviez** [comment] 2023-06-27 06:47
Cool - going to close this issue out. Even if the cluster were to halt again, debugging would involve looking at more specifics, so I think a new issue would be in order anyways.

**Closed by steviez** 2023-06-27 06:47 UTC
