### ISSUE TITLE
Rust BPF: Rust's built-in 128-bit handling is ABI incompatbile

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#5716] opened 2019-08-28 22:50 UTC
#### Problem

Rust's compiler-builtins include Rust implementations of the LLVM math builtins..  The 128-bit flavors compile into non-ABI compatible versions.  Specifically they assume that the 128 bit parameters are passed on the stack, whereas normally a 128-bit value is passed via two registers.  It's unclear where this ABI incompatibility is coming from.

#### Proposed Solution

The current work-around is to use the LLVM C versions of the builtins which are ABI compatible.

The purpose of this issue to dig deeper to find out why and ensure that why does not affect anything else we care about.

**Comment by dmakarov** [comment] 2021-02-22 12:36
It seems the problem is that when a rust intrinsic function such as `__multi3` is called the parameters are passed as values of a primitive type `i128`, but `__multi3` treats the parameters as values of an aggregate type `int::LargeInt`.  The missing part seems to be the wrapping of `i128` parameters in `int::LargeInt`, and unwrapping of the result back to `i128`.

**Comment by dmakarov** [comment] 2021-02-26 11:16
PR https://github.com/solana-labs/rust/pull/8 should fix this issue.  Regardless of the ABI fixes, we should use compiler-rt implementation of intrinsic functions, as these are currently more efficient than their Rust counterparts.

**Comment by dmakarov** [comment] 2021-02-26 18:55
The fix was merged https://github.com/solana-labs/rust/pull/8/commits/e2db9fb724f1d5c08846e6b814e2a44630832076

**Closed by dmakarov** 2021-02-26 18:55 UTC
Labels: bug
