### ISSUE TITLE
getHealth API not working as expect

### ISSUE THREAD

**Issue by jasoncsli** [solana-labs/solana#27737] opened 2022-09-13 02:49 UTC
#### Problem
The monitor command and getHealthApi showed that the validator is behind. But When I use the catchup command, it shows that I am in sync with the newest block. This problem has been for one hour.

```
⠂ 354:15:48 | 1766 slots behind | Processed Slot: 150421263 | Confirmed Slot: 150421263 | Finalized Slot: 150421229 | Full Snapshot Slot:

sudo solana  catchup --our-localhost
xx has caught up (us:150421907 them:150421917)
```

```
curl http://localhost:8899 -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0","id":1, "method":"getHealth"}
'
{"jsonrpc":"2.0","error":{"code":-32005,"message":"Node is behind by 1906 slots","data":{"numSlotsBehind":1906}},"id":1}
```

I can get the correct slot from getSlot Api, and I can also get the newest block data. What happened to my validator?

version: 1.10.35

**Comment by seal** [comment] 2022-09-23 16:31
Take a peek here:
https://github.com/solana-labs/solana/issues/16957

it compares local to solana blockchain, etc
It's normal to be behind a bit

**Comment by steviez** [comment] 2023-06-02 22:40
Closing this issue out - it is dated so it is unclear if the original poster is still encountering this issue. In the event that they are, the linked issue has more details and discussion around the cause of the issue as well as possible solutions.

**Closed by steviez** 2023-06-02 22:40 UTC
Labels: community, validator
