### ISSUE TITLE
`solana-test-validator` deadlock

### ISSUE THREAD

**Issue by cavemanloverboy** [solana-labs/solana#30557] opened 2023-02-28 04:16 UTC
#### Problem
When using a `solana-test-validator` with `--slots-per-epoch=32 --ticks-per-slot=1`, the test validator seems to sometimes deadlock at a particular slot early on after startup. "Deadlock" here means that I don't see the slot counter progress, and all transactions submitted to the test cluster time out.

This was reproduced on my fork of bleeding edge, but also 1.14.12, 1.13.6 on two machines (ARM, x86).

Raising `ticks-per-slot` to 32 or 64 alleviated the deadlock, but this remains an issue.

**Comment by cavemanloverboy** [comment] 2023-02-28 07:49
demo:
https://user-images.githubusercontent.com/93507302/221787792-9b2b4558-9f97-40db-ad99-feef7cf4e50b.mov

**Comment by bw-solana** [comment] 2023-03-08 21:45
Not sure exactly how we want to resolve... seems we're only at risk when ticks per slot is really small (so that we're at risk of missing leader slots) and `--slots-per-epoch` is very small (e.g. equal to tower size). We could enforce `--ticks-per-slot` equal to 2 or more or some more complex requirements based on what `--slots-per-epoch` is set to.

@t-nelson what do you think?

**Comment by mvines** [comment] 2023-03-08 21:49
Requiring 2 minimum seems fine to me. There doesnt seem like there’s any practical reason to use 1 over 2 anyway

**Comment by c410-f3r** [comment] 2023-04-02 18:31
Just a heads up.

For whatever the reason, I am getting the same behaviour using `--ticks-per-slot 16` instead of `--ticks-per-slot 2` in `399b7ba7` but I am not sure if my problem has the same root cause of this issue.

**Comment by cavemanloverboy** [comment] 2023-04-03 19:23
I had also noticed it at 16, for what it's worth

**Comment by bw-solana** [comment] 2023-04-04 00:11
@c410-f3r @cavemanloverboy - Any idea if test validator is skipping slots when you have ticks set to 16? Does it fail every time? Which slot does it get stuck at?

**Comment by t-nelson** [comment] 2023-04-06 17:36
are you consistently using the target rust version for a given branch?  there've been some struct packing changes that might affect the runtime in various situations and potentially lead to what appears to be a "deadlock".

always use the `./cargo` wrapper to build from source to avoid inconsistency.

**Comment by bw-solana** [comment] 2023-04-06 22:18
I'm able to reproduce this when running long enough with `--slots-per-epoch=32` and `--ticks-per-slot=2` (takes hundreds of slots running on server grade HW).

Looks like the same symptom where we stop generating blocks because the leader schedule hasn't been populated for the epoch we're entering. This is because finalized slot is >32 slots behind current slot (i.e. the size of the epoch).

Root cause appears different in this case because I'm not seeing skipped slots. It looks like the following is the root cause:

1. There is a race condition for votes landing (sometimes they're slow relative to the fast PoH tick)
2. We skip future votes due to failing the vote threshold (if the vote from 8 slots ago hasn't landed yet)
3. Finalized slots  > epoch slots behind the current slot
4. We don't generate the leader schedule for the next epoch in time
5. We don't populate the working bank because we don't know leader schedule
6. We stop making blocks

If I bypass the vote threshold check, I'm seeing test validator run for tens of thousands of slots.

Not sure what the right long term fix is for this... More ticks per slot helps ensure votes will land in time. Increasing slots per epoch is probably the safer thing as this will allow us to skip a few slots/votes and still function.

**Comment by bw-solana** [comment] 2023-04-07 14:55
As a workaround, I'm seeing my validator was able to run for 16 hours+ with `--slots-per-epoch=64` and `--ticks-per-slot=2`

**Closed** 2023-04-25 15:02 UTC
Labels: community
