### ISSUE TITLE
Flawed inflationRewards API?

### ISSUE THREAD

**Issue by xdzurman** [solana-labs/solana#19151] opened 2021-08-10 13:16 UTC
#### Problem
Hello! Please help, check out this account https://explorer.solana.com/address/C3QvGBUGEBnC3WdBRXcndxMDFE8WdpTb9e3Rn3Lg1bcp/rewards?cluster=devnet it says that the balance is 0.010732416 SOL. The sum of rewards page is 0.00069756. I delegated exactly 0.01 SOL, however the difference between initial balance and the reward amount is 0.000034856. Where did this difference come from? The amount seems awful lot like another reward amount. Is the reward API flawed because it did not catch this value? Or am I missing something?

**Comment by mvines** [comment] 2021-08-10 16:28
This issue like this is a crosspost from Discord, so closing this as a duplicate: https://discord.com/channels/428295358100013066/428295358100013069/874641922633912322

**Closed by mvines** 2021-08-10 16:28 UTC

**Comment by CriesofCarrots** [comment] 2021-08-10 17:08
For posterity: the issue is that the devnet long-term storage is missing a chunk of data overlapping the epoch 162 boundary, so rewards information is not available for that epoch.
