### ISSUE TITLE
SystemInstructions link on docs.solana.com does not work for version 1.9.9

### ISSUE THREAD

**Issue by GregoryNEUT** [solana-labs/solana#23326] opened 2022-02-24 10:14 UTC
#### Problem

**SystemInstructions** link on the [Solana Docs](https://docs.solana.com/developing/runtime-facilities/programs) does not work with version 1.9.9.

![Screenshot 2022-02-24 at 11 08 40](https://user-images.githubusercontent.com/22965416/155503691-0e9e1d3c-f0b8-47a0-9aba-133af7ede380.png)

Leads to:

![Screenshot 2022-02-24 at 18 42 05](https://user-images.githubusercontent.com/22965416/155578296-56a09418-c7f5-42bc-8e51-1e750deea9f3.png)

FYI Works in 1.9.6:
https://docs.rs/solana-sdk/1.9.6/solana_sdk/system_instruction/enum.SystemInstruction.html

#### Proposed Solution

Either make the link to work, or if the targeted enum doesn't exist anymore, state that the first link works for versions `<= 1.9.6` and insert a new link for version `>= 1.9.7`, like:

Instructions (1.9.6 and lower): [SystemInstruction](https://docs.rs/solana-sdk/1.9.9/solana_sdk/system_instruction/enum.SystemInstruction.html)
Instructions (1.9.7 and upper): _new link_

Code path: docs/src/developing/runtime-facilities/programs.md

**Comment by t-nelson** [comment] 2022-02-24 16:39
screenshots seem a bit excessive.  A PR would be much appreciated though

**Comment by migui3230** [comment] 2022-02-25 21:03
Ill take this issue on!

**Comment by anantasty** [comment] 2022-02-27 01:12
@migui3230 it seems like the `system_instruction` module is not included [in the docs](https://docs.rs/solana-sdk/1.9.9/solana_sdk/) for the current version. Although building the docs locally  using `cargo doc` generates docs for the  `system_instruction` module.

**Comment by migui3230** [comment] 2022-03-03 20:52
So do I just wait for the new link to add that or is there any other solution for this?

**Comment by jstarry** [comment] 2022-04-16 15:57
I did a git bisect and discovered that #22873 caused this regression, @brson could you take a look?

**Comment by brson** [comment] 2022-04-16 20:17
Yeah I'll investigate.

**Comment by brson** [comment] 2022-04-20 21:24
I've learned a bit about how to work around the problem, but don't quite understand what is happening. Certainly one of rustdoc's heuristics relating to reexports is getting tripped up. While it should probably be fixed in rustdoc if it can be, probably we'll just hack around it.

This is related to the `example_mocks` module in solana_program and to the `pub use solana_program::*` reexport in solana_sdk. Within `example_mocks` is a reexport of several top-level modules from `solana_program`.

What appears to be happening is that during compilation of the solana_sdk docs, rustdoc decides that those deeply-buried reexports in `example_mocks` are sort-of the "canonical" reexports and generates them; then subsequently does not generate docs for the reexports that we care about from the top level of solana_sdk.

The analysis that results in this phenomenon appears to be lexical, dependent on source ordering. So if we just move the `mod example_mocks` declaration to the very bottom of `solana_program/src/lib.rs` then the `*`-import of the solana_program crate within solana_sdk gives `example_mocks` less priority, resulting in the module docs to appear as expected (and disappear within the example_mocks::solana_sdk module).

Doing that module reordering just to fix this problem is brittle though, so I'd like to find another way. Ideally the fix would be in rustdoc, but I don't know yet if I want to dive into that. I am thinking of moving `solana_sdk::example_mocks` and `solana_program::example_mocks` into a their own crate, where they won't be in the way

**Comment by brson** [comment] 2022-04-20 21:25
This also affects other modules too - `instruction` at least.

**Comment by brson** [comment] 2022-04-20 23:55
`example_mocks` can't be extracted to its own crate because it will create an unpublishable circular dependency with `solana_program`.

**Comment by jstarry** [comment] 2022-04-21 07:09
I'm ok with a hacky workaround as long as there's a comment that explains the context for the hack to hopefully avoid it breaking again in the future.

**Closed** 2022-04-22 06:43 UTC
Labels: good first issue
