### ISSUE TITLE
solana windows installer link not working

### ISSUE THREAD

**Issue by CLIcoder** [solana-labs/solana#20368] opened 2021-10-01 09:48 UTC
#### Problem

the link :  https://release.solana.com/v1.7.14/solana-install-init-x86_64-pc-windows-msvc.exe

No source code for windows also

**Comment by macfromtheblock** [comment] 2021-10-01 23:20
I think they are on it. I posted too.
Meanwhile i'm using version 1.7.12

**Comment by CriesofCarrots** [comment] 2021-10-01 23:34
Thanks, closing as dupe of #20382

**Closed by CriesofCarrots** 2021-10-01 23:34 UTC
