### ISSUE TITLE
solana balance usb://ledger ignores argument

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#8857] opened 2020-03-13 23:44 UTC
#### Problem

`solana balance usb://ledger` ignores the `usb://ledger` argument and returns the balance of the default signer.

#### Proposed Solution

Display the balance of the public key at usb://ledger.

cc: @CriesofCarrots @t-nelson

**Comment by CriesofCarrots** [comment] 2020-03-14 00:12
This is caused by issue #8852 , and will be resolved by that fix

**Closed** 2020-03-16 22:17 UTC
