### ISSUE TITLE
Unreasonable writes to disk with RocksDB

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#8116] opened 2020-02-04 18:02 UTC
#### Problem

RocksDB write amplification is too high and causes too much writing to disk even in an idling cluster.

![image](https://user-images.githubusercontent.com/44789711/73772311-c4921180-4734-11ea-95a5-5060e87d8183.png)
Based on that image above, it appears as though a low priority RocksDB thread is causing these excessive writes to disk. That seems to indicate something with the background flushes or compaction. 

![image](https://user-images.githubusercontent.com/44789711/73772284-b9d77c80-4734-11ea-916c-dcc5ffb6fc23.png)

#### Proposed Solution

Figure out which params can be updated to reduce the write amplification
https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide#amplification-factors

**Comment by brianlong** [comment] 2020-02-06 18:54
Hi @sunnygleason I am the node-operator who provided the screenshots above. I am happy to help you with log files, etc. from my node. Also, let me know if you would like me to experiment with different rocksdb options.

**Comment by sunnygleason** [comment] 2020-02-06 19:51
@brianlong sounds great - please feel free to provide any additional info to reproduce, or tuning experiments you may run. I'm bringing a test platform up and will do the same!

**Comment by brianlong** [comment] 2020-02-06 20:10
I'm still not sure how to reproduce the problem from scratch. My SLP node has the problem, but my TDS node does not. In this seven day chart, you can see the initial burst of disc I/O when I started the node. Then I/O was managable. Then it wasn't.
<img width="488" alt="Screen Shot 2020-02-06 at 1 08 33 PM" src="https://user-images.githubusercontent.com/79186/73974583-d6fd7e00-48e1-11ea-8798-6831f038bcbd.png">

**Comment by brianlong** [comment] 2020-02-06 20:26
FWIW, that happened after the most recent software update. So, there could have been a change to the rocksDB options that caused the change in behavior.

Deleting the ledger and restarting the validator doesn't help either. When I look at the `/validator-ledger/rocksdb/LOG`, I see a bunch of activity related to compacting the DB. It seems like it is continuously reorganizing & compacting files without pausing to take a break.

Compaction jobs like this `2020/02/06-12:22:03.709602 7fb2a0d74700 [db/compaction_job.cc:1337] [transaction_status] [JOB 313113] Generated table #437954: 575557 keys, 108187476 bytes` are triggered every second.

I am not sure why we need to be so aggressive with compaction on immutable ledger entries. Each record is written once, read many times, and deleted when no longer needed. Compacting the DB is only required to clean up the deleted records. Is there a setting in the `/validator-ledger/rocksdb/OPTIONS-*` file that controls how often the DB is compacted? If so, I can change that setting here and restart my node. Cleaning up after deleted records could happen once per epoch, day, etc.

I can also make other changes to /validator-ledger/rocksdb/OPTIONS-* and we can see what happens here.

**Comment by brianlong** [comment] 2020-02-07 18:48
@sunnygleason Comparing the rocksdb OPTIONS files from my tds node (v. 0.23.2) shows two sections not included in my slp node (v. 0.22.7). Those sections are `[CFOptions "duplicate_slots"]` and `[TableOptions/BlockBasedTable "duplicate_slots"]`. I wonder if the newer OPTIONS file explains the difference in I/O between the two nodes.

**Comment by sunnygleason** [comment] 2020-02-07 20:54
@brianlong thank you so much for the information. I've been able to confirm that the issue isn't present on my AWS node running 0.23.1 against testnet.solana.com: the max disk utilization is on the order of several tens of MB/s.

![image](https://user-images.githubusercontent.com/153621/74064755-58780d80-49c1-11ea-90bc-c91ea5ac33c2.png)

Based on this, it seems reasonable to proceed along the path of investigating the issue in the 0.22.7 series rather than trying to reproduce under 0.23.1. Then, we can use that knowledge to guide examination of the 0.23.x series (and later)?

We have done work to reclaim storage under rocksdb -- I think you're right that there is work to do in balancing steady-state with lightly-loaded performance. It's somewhat tricky because the longer interval between compaction runs could mean increased work per run, with yet-to-be measured impact on latency.

I created a benchmark tool to tune ledger performance -- if you're so inclined, it might be
useful in reproducing the issue outside of a full network. I'll be trying it out as well.

https://github.com/solana-labs/solana/blob/master/core/tests/ledger_cleanup.rs

Let me know what you think, thank you again for your tenacity and useful information!

**Comment by brianlong** [comment] 2020-02-09 19:35
@sunnygleason See attached for more data from my SLP node. The actual file names are not being written to the LOG, so I grabbed `ls -l` snapshots over 10 & 45 minutes to show the high churn rate.
[solana-slp-bad.txt](https://github.com/solana-labs/solana/files/4177598/solana-slp-bad.txt)

**Comment by brianlong** [comment] 2020-02-09 19:39
Pete (LunaNova) also mentioned that his SLP node had high I/O and his TdS node was OK. I see that there were several changes to blocktree.rs/blockstore.rs from 0.22 to 0.23 dealing with excess threads & duplicate slots. https://github.com/solana-labs/solana/compare/v0.22...v0.23

I wonder if simply backporting the blockstore changes to a new version 0.22.n will resolve this issue. Thoughts?

**Comment by mvines** [comment] 2020-02-10 00:05
Oh if we're only seeing this on 0.22 and not on 0.23 then I don't think we need to bother backporting (or even pursue this issue any further) as 0.22 will be retired in a couple weeks anyway

**Comment by sunnygleason** [comment] 2020-02-10 15:51
@mvines that's what I seem to be seeing, here are my rough benchmark runs to get an idea of what might be happening:

![image](https://user-images.githubusercontent.com/153621/74165370-fef72500-4bf2-11ea-906e-a0d65954aca8.png)

v0.22.x low peak(s), v0.23.x high peak

This is just my first draft info though, so take with a grain of salt, I'm re-running the benchmarks to pin this down and will update when I have more credible info.

**Comment by mvines** [comment] 2020-02-10 17:39
Let's sit on this until we observe it happening on 0.23 or later

**Comment by brianlong** [comment] 2020-02-11 16:55
As we monitor this, I will keep posting data so we can come back to it later. I saw a major jump in the size of the rocksdb folder this morning. There were 1,885 *.sst files of 104MB each in my folder. I don't know what caused the jump. At the moment my storage is full and my node is dead. I will try to pull the logs and then re-start.

<img width="504" alt="Screen Shot 2020-02-11 at 9 47 17 AM" src="https://user-images.githubusercontent.com/79186/74258945-59a48580-4cb4-11ea-85be-d1cb89e345b6.png">

**Comment by mvines** [comment] 2020-02-11 20:15
This latest rocksdb folder size appears to be due to the removal of the `--limit-ledger-size` argument (ie, works as designed)

**Comment by brianlong** [comment] 2020-02-11 20:20
Agreed. The jump condition was surprising, but there are bigger issues to focus on right now. I will keep watching I/O rates.

**Comment by mvines** [comment] 2020-03-09 15:35
(bumping this issue to high-priority, it's a point of concern for multiple validators)

**Comment by ryoqun** [comment] 2020-03-11 09:15
`$ iotop -d 10` clealy blames rocksdb. This slows down my machine... Poor SSD...

```
Total DISK READ :      11.94 K/s | Total DISK WRITE :     140.73 M/s
Actual DISK READ:      11.94 K/s | Actual DISK WRITE:      78.05 M/s
  TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND                                                                                                                                                                    
 3974 be/4 ubuntu      0.00 B/s   69.77 M/s  0.00 % 16.95 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:low2]
 3978 be/4 ubuntu      0.00 B/s   32.99 M/s  0.00 %  5.96 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:low6]
 3979 be/4 ubuntu      0.00 B/s   13.83 M/s  0.00 %  4.55 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:low7]
 6524 be/4 root        0.00 B/s   74.84 K/s  0.00 %  2.88 % [kworker/u16:0]
 3975 be/4 ubuntu      0.00 B/s   12.42 M/s  0.00 %  2.05 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:low3]
21322 be/4 root        0.00 B/s   41.40 K/s  0.00 %  1.56 % [kworker/u16:4]
 3973 be/4 ubuntu      0.00 B/s    8.65 M/s  0.00 %  1.47 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:low1]
21136 be/4 root        0.00 B/s  111.46 K/s  0.00 %  1.27 % [kworker/u16:15]
 5027 be/4 root        0.00 B/s  124.20 K/s  0.00 %  1.08 % [kworker/u16:7]
 3980 be/4 ubuntu      0.00 B/s  431.12 K/s  0.00 %  0.91 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~zoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:high0]
 3981 be/4 ubuntu      0.00 B/s  558.91 K/s  0.00 %  0.65 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~zoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:high1]
 6598 be/4 root        0.00 B/s   66.88 K/s  0.00 %  0.64 % [kworker/u16:13]
 4990 be/4 root        0.00 B/s  209.39 K/s  0.00 %  0.36 % [kworker/u16:22]
 3645 be/4 root        0.00 B/s   68.87 K/s  0.00 %  0.14 % [kworker/u16:12]
 6582 be/4 root        0.00 B/s   58.12 K/s  0.00 %  0.14 % [kworker/u16:1]
 3644 be/4 root        0.00 B/s  107.08 K/s  0.00 %  0.12 % [kworker/u16:2]
 4996 be/4 root        0.00 B/s   91.56 K/s  0.00 %  0.11 % [kworker/u16:24]
 5028 be/4 root        0.00 B/s  168.39 K/s  0.00 %  0.11 % [kworker/u16:8]
 3977 be/4 ubuntu      0.00 B/s   57.72 K/s  0.00 %  0.08 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:low5]
 4371 be/4 ubuntu      5.97 K/s    0.00 B/s  0.00 %  0.07 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [blockstore_2]
 4370 be/4 ubuntu      2.79 K/s    0.00 B/s  0.00 %  0.07 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [blockstore_1]
 4369 be/4 ubuntu      0.00 B/s    0.00 B/s  0.00 %  0.07 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [blockstore_0]
 4348 be/4 root        0.00 B/s   53.34 K/s  0.00 %  0.06 % [kworker/u16:9]
 4372 be/4 ubuntu      3.18 K/s    0.00 B/s  0.00 %  0.06 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [blockstore_3]
 6536 be/4 root        0.00 B/s  106.69 K/s  0.00 %  0.06 % [kworker/u16:5]
 6547 be/4 root        0.00 B/s  104.30 K/s  0.00 %  0.04 % [kworker/u16:11]
 4981 be/4 root        0.00 B/s  142.51 K/s  0.00 %  0.03 % [kworker/u16:19]
 3976 be/4 ubuntu      0.00 B/s    7.17 K/s  0.00 %  0.02 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:low4]
18658 be/4 root        0.00 B/s  172.77 K/s  0.00 %  0.02 % [kworker/u16:10]
 3972 be/4 ubuntu      0.00 B/s    7.17 K/s  0.00 %  0.02 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~nzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [rocksdb:low0]
 6286 be/4 root        0.00 B/s   83.20 K/s  0.00 %  0.01 % [kworker/u16:3]
 6605 be/4 root        0.00 B/s   33.04 K/s  0.00 %  0.01 % [kworker/u16:14]
 3970 be/4 ubuntu      0.00 B/s 1222.91 B/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~zoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [solana-gossip]
 4195 be/4 ubuntu      0.00 B/s  815.28 B/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~zoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [solana-gossip]
 4203 be/4 ubuntu      0.00 B/s  407.64 B/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~zoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [solana-listen]
 4238 be/4 ubuntu      0.00 B/s  214.57 K/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~MAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [solana-window-i]
 4245 be/4 ubuntu      0.00 B/s   35.43 K/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~MAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [solana-replay-s]
 4246 be/4 ubuntu      0.00 B/s  407.64 B/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~MAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [solana-ledger-c]
 4365 be/4 ubuntu      0.00 B/s    2.79 K/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~MAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [blockstore_proc]
 4366 be/4 ubuntu      0.00 B/s    6.37 K/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~MAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [blockstore_proc]
 4367 be/4 ubuntu      0.00 B/s 1222.91 B/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~MAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [blockstore_proc]
 4368 be/4 ubuntu      0.00 B/s    5.18 K/s  0.00 %  0.00 % ./solana-validator --ledger ledger --expected-shred-version 18216 --entrypoint 35.203.~MAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --no-snapshot-fetch [blockstore_proc]
    1 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % init
    2 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kthreadd]
    4 be/0 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [kworker/0:0H]
    6 be/0 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [mm_percpu_wq]
    7 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [ksoftirqd/0]
    8 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % [rcu_sched]

```

**Comment by sakridge** [comment] 2020-03-31 15:19
This should be fixed by https://github.com/solana-labs/solana/pull/9131

**Comment by sakridge** [comment] 2020-03-31 15:19
Issue is we doing compaction 100% of the time when a validator restarts.

**Comment by mvines** [comment] 2020-03-31 15:40
Let's close this issue then, and if we still have similar symptoms then a new issue can always be created for that future work.

@brianlong - v1.0.12 contains the #9131, and is available for use on either TdS or mainnet-beta (I just haven't announced it yet on Discord)

**Closed by mvines** 2020-03-31 15:40 UTC
Labels: monitor
