### ISSUE TITLE
`logsSubscribe` is broken and misses events

### ISSUE THREAD

**Issue by skynetcapital** [solana-labs/solana#18827] opened 2021-07-21 23:23 UTC
#### Problem
`logsSubscribe` functions like it is broken and misses events.
For example, I'll subscribe to a program id's pubkey. I'll get maybe half of the transactions that come through interacting with it. We've observed this behavior with 2 client libraries, Solnet and SolanaJ.

#### Proposed Solution
Investigate and resolve the bug.

#### Related issues
(https://github.com/solana-labs/solana/issues/18587), (https://github.com/solana-labs/solana/issues/9909) (https://github.com/solana-labs/solana/issues/18197)

**Comment by lijunwangs** [comment] 2021-08-03 07:36
I am investigating  #18587 and noticed this issue. @skynetcapital Do you have a reproducer for this issue?

**Comment by lijunwangs** [comment] 2021-08-06 00:20
According to my analysis this is a dupe of  #18587 -- different symptoms of the same root cause

**Comment by lijunwangs** [comment] 2021-08-12 23:36
Fixes have been merged into master 1a372a792ec4a646a24ad2faaac9793d84784757. Please verify once build available

**Closed by lijunwangs** 2021-08-12 23:36 UTC
