### ISSUE TITLE
solana deploy is old, and should be indicated so from CLI

### ISSUE THREAD

**Issue by DuwYAnne** [solana-labs/solana#27834] opened 2022-09-16 04:08 UTC
#### Problem
When deploying a program, its easy to forget to include the program keyword (as I've done), and instead type
`solana deploy <program address>`, this uses an old loader which creates an immutable program and locks up all sol.
For instance, I was testing a program which had 1 SOL in rent, and now need to redeploy.

#### Proposed Solution
Give a warning along the lines of,
`This is an old loader, and any program deployed is immutable`

**Comment by KirillLykov** [comment] 2022-09-16 15:50
Thanks for reporting! I will check this out soon

**Comment by CriesofCarrots** [comment] 2022-09-16 15:52
Dupe of https://github.com/solana-labs/solana/issues/27228, which prompted this: https://github.com/solana-labs/solana/pull/27264

**Comment by jstarry** [comment] 2022-09-19 11:34
> Dupe of #27228, which prompted this: #27264

That's great but I'm now wondering if we should go further and remove this subcommand altogether. There's no real value in it.

**Comment by sakridge** [comment] 2022-09-19 11:48
How about renaming it `solana deploy-immutable` or something like that? Is there another newer way to deploy an immutable program?

**Comment by jstarry** [comment] 2022-09-19 14:20
Yeah, you can deploy an upgradeable program with the `--final` flag and it will remove the upgrade authority which makes a program immutable

**Comment by CriesofCarrots** [comment] 2022-09-19 15:29
Of those two solutions, I'm in favor of removing it, since a rename is just as breaking.

**Comment by KirillLykov** [comment] 2022-10-13 17:16
In the documentation, we have `The solana deploy and solana program deploy CLI commands use the upgradeable BPF loader.` 
But in fact, for `solana deploy` we use non-upgradeable loader, see https://github.com/solana-labs/solana/blob/master/cli/src/program.rs#L1721
Since the consensus is to remove`solana deploy` , this will not be a problem.

My understanding is that currently `solana deploy` and `solana program deploy --final` use different loader which probably should not be the case (from documentation).
I wonder if someone is using `solana deploy` currently and it is important for that user that a particular loader is used.

**Comment by jstarry** [comment] 2022-10-17 01:01
>  I wonder if someone is using solana deploy currently and it is important for that user that a particular loader is used.

It's possible but they can find another way to deploy with that loader if they really need it. Most users should be fine using the upgradeable loader.

**Comment by KirillLykov** [comment] 2022-10-17 18:41
> > I wonder if someone is using solana deploy currently and it is important for that user that a particular loader is used.
> 
> It's possible but they can find another way to deploy with that loader if they really need it. Most users should be fine using the upgradeable loader.

I've updated tests for immutable deploy (`solana deploy` -> `solana program deploy` code path). To be sure that everything is as expected, I should say that there are some, probably minor, differences in behavior: https://github.com/solana-labs/solana/pull/28398
When these tests are upgraded, I will finalize the the follow up https://github.com/solana-labs/solana/pull/28399 which removes `solana deploy` completely

**Comment by KirillLykov** [comment] 2022-10-19 13:55
Done

**Closed by KirillLykov** 2022-10-19 13:55 UTC
Labels: community
